defmodule AshFoundationLab.GeneratedMigrationReviewTest do
  use ExUnit.Case, async: true

  @review_root Path.expand("../../priv/generated_migration_review", __DIR__)

  test "the generated baseline contains the required tenant and database safety primitives" do
    source = migration_source()

    assert source =~ "This file was autogenerated with `mix ash_postgres.generate_migrations`"
    assert length(Regex.scan(~r/add\(:tenant_id, :uuid, null: false\)/, source)) == 3

    for index_name <- [
          "actors_tenant_id_index",
          "actors_id_tenant_id_index",
          "foundation_records_tenant_id_index",
          "foundation_records_id_tenant_id_index",
          "foundation_records_tenant_id_audit_reference_index",
          "outbox_events_tenant_id_audit_reference_index",
          "outbox_events_tenant_id_occurred_at_id_index",
          "outbox_events_tenant_id_aggregate_type_aggregate_id_index"
        ] do
      assert source =~ ~s(name: "#{index_name}")
    end

    for foreign_key_name <- [
          "actors_tenant_id_fkey",
          "foundation_records_tenant_id_fkey",
          "outbox_events_tenant_id_fkey",
          "outbox_events_actor_tenant_fkey",
          "outbox_events_aggregate_tenant_fkey"
        ] do
      assert source =~ ~s(name: "#{foreign_key_name}")
    end

    assert length(Regex.scan(~r/with: \[tenant_id: :tenant_id\]/, source)) == 2
    assert length(Regex.scan(~r/match: :full/, source)) == 2

    for constraint_name <- [
          "actor_name_must_not_be_empty",
          "actor_kind_must_be_known",
          "name_must_not_be_empty",
          "foundation_record_status_must_be_known",
          "foundation_record_lock_version_must_be_positive",
          "submitted_record_requires_audit_reference",
          "outbox_aggregate_type_must_not_be_empty",
          "outbox_event_type_must_not_be_empty",
          "outbox_schema_version_must_be_positive",
          "outbox_classification_must_be_internal",
          "outbox_payload_must_be_an_object",
          "tenant_name_must_not_be_empty"
        ] do
      assert source =~ constraint_name
    end
  end

  test "the generated baseline has an additive up path and an explicit down path" do
    source = migration_source()
    [up, down] = String.split(source, "  def down do", parts: 2)

    assert up =~ "  def up do"
    refute up =~ "remove("
    refute up =~ "drop("
    refute up =~ "drop_if_exists("

    for table <- [:outbox_events, :foundation_records, :actors, :tenants] do
      assert down =~ "drop(table(:#{table}))"
    end

    assert down =~ ~s|drop(constraint(:outbox_events, "outbox_events_actor_tenant_fkey"))|

    assert down =~
             ~s|drop(constraint(:outbox_events, "outbox_events_aggregate_tenant_fkey"))|
  end

  test "the generated idempotency migration preserves the transactional claim constraints" do
    source = idempotency_migration_source()

    assert source =~ "This file was autogenerated with `mix ash_postgres.generate_migrations`"
    assert source =~ "create table(:action_idempotency_keys, primary_key: false)"

    for index_name <- [
          "action_idempotency_keys_tenant_action_key_index",
          "action_idempotency_keys_tenant_inserted_id_index",
          "action_idempotency_keys_tenant_aggregate_index"
        ] do
      assert source =~ ~s(name: "#{index_name}")
    end

    for foreign_key_name <- [
          "action_idempotency_keys_tenant_id_fkey",
          "action_idempotency_keys_actor_tenant_fkey",
          "action_idempotency_keys_aggregate_tenant_fkey"
        ] do
      assert source =~ ~s(name: "#{foreign_key_name}")
    end

    assert length(Regex.scan(~r/with: \[tenant_id: :tenant_id\]/, source)) == 2
    assert length(Regex.scan(~r/match: :full/, source)) == 2

    for constraint_name <- [
          "action_idempotency_action_name_must_not_be_empty",
          "action_idempotency_aggregate_type_must_not_be_empty",
          "action_idempotency_request_hash_must_be_sha256",
          "action_idempotency_status_must_be_known",
          "action_idempotency_completion_must_be_consistent",
          "action_idempotency_result_lock_version_must_be_positive"
        ] do
      assert source =~ constraint_name
    end

    [up, down] = String.split(source, "  def down do", parts: 2)
    refute up =~ "remove("
    refute up =~ "drop("
    refute up =~ "drop_if_exists("
    assert down =~ "drop(table(:action_idempotency_keys))"
  end

  defp migration_source do
    migration_glob =
      Path.join([
        @review_root,
        "migrations",
        "*_phase0_generated_baseline_review.exs"
      ])

    assert [migration_path] = Path.wildcard(migration_glob)
    File.read!(migration_path)
  end

  defp idempotency_migration_source do
    migration_glob =
      Path.join([
        @review_root,
        "migrations",
        "*_phase0_generated_idempotency_review.exs"
      ])

    assert [migration_path] = Path.wildcard(migration_glob)
    File.read!(migration_path)
  end
end
