defmodule AshFoundationLab.Repo.Migrations.Phase0GeneratedBaselineReview do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:actors, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:name, :text, null: false)
      add(:kind, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create index(:actors, [:tenant_id], name: "actors_tenant_id_index")

    create index(:actors, [:id, :tenant_id], name: "actors_id_tenant_id_index", unique: true)

    create table(:foundation_records, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:name, :text, null: false)
      add(:status, :text, null: false, default: "draft")
      add(:lock_version, :bigint, null: false, default: 1)
      add(:audit_reference, :uuid)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create index(:foundation_records, [:tenant_id], name: "foundation_records_tenant_id_index")

    create index(:foundation_records, [:id, :tenant_id],
             name: "foundation_records_id_tenant_id_index",
             unique: true
           )

    create table(:outbox_events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :actor_id,
        references(:actors,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "outbox_events_actor_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ), null: false)

      add(:aggregate_type, :text, null: false)

      add(
        :aggregate_id,
        references(:foundation_records,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "outbox_events_aggregate_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ), null: false)

      add(:event_type, :text, null: false)
      add(:schema_version, :bigint, null: false)
      add(:correlation_id, :uuid, null: false)
      add(:causation_id, :uuid, null: false)
      add(:audit_reference, :uuid, null: false)
      add(:classification, :text, null: false)
      add(:payload, :map, null: false)
      add(:occurred_at, :utc_datetime_usec, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create index(:outbox_events, [:tenant_id, :audit_reference],
             name: "outbox_events_tenant_id_audit_reference_index",
             unique: true
           )

    create index(:outbox_events, [:tenant_id, :occurred_at, :id],
             name: "outbox_events_tenant_id_occurred_at_id_index"
           )

    create index(:outbox_events, [:tenant_id, :aggregate_type, :aggregate_id],
             name: "outbox_events_tenant_id_aggregate_type_aggregate_id_index"
           )

    create table(:tenants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:actors) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "actors_tenant_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create constraint(:actors, :actor_name_must_not_be_empty,
             check: """
               char_length(name) > 0
             """
           )

    create constraint(:actors, :actor_kind_must_be_known,
             check: """
               kind IN ('human', 'service')
             """
           )

    alter table(:foundation_records) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "foundation_records_tenant_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create constraint(:foundation_records, :name_must_not_be_empty,
             check: """
               char_length(name) > 0
             """
           )

    create constraint(:foundation_records, :foundation_record_status_must_be_known,
             check: """
               status IN ('draft', 'in_review')
             """
           )

    create constraint(:foundation_records, :foundation_record_lock_version_must_be_positive,
             check: """
               lock_version >= 1
             """
           )

    create constraint(:foundation_records, :submitted_record_requires_audit_reference,
             check: """
               status <> 'in_review' OR audit_reference IS NOT NULL
             """
           )

    create index(:foundation_records, [:tenant_id, :audit_reference],
             name: "foundation_records_tenant_id_audit_reference_index",
             unique: true,
             where: "audit_reference IS NOT NULL"
           )

    alter table(:outbox_events) do
      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "outbox_events_tenant_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create constraint(:outbox_events, :outbox_aggregate_type_must_not_be_empty,
             check: """
               char_length(aggregate_type) > 0
             """
           )

    create constraint(:outbox_events, :outbox_event_type_must_not_be_empty,
             check: """
               char_length(event_type) > 0
             """
           )

    create constraint(:outbox_events, :outbox_schema_version_must_be_positive,
             check: """
               schema_version >= 1
             """
           )

    create constraint(:outbox_events, :outbox_classification_must_be_internal,
             check: """
               classification = 'internal'
             """
           )

    create constraint(:outbox_events, :outbox_payload_must_be_an_object,
             check: """
               jsonb_typeof(payload) = 'object'
             """
           )

    alter table(:tenants) do
      add(:name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:tenants, :tenant_name_must_not_be_empty,
             check: """
               char_length(name) > 0
             """
           )
  end

  def down do
    drop_if_exists(constraint(:tenants, :tenant_name_must_not_be_empty))

    alter table(:tenants) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:name)
    end

    drop_if_exists(constraint(:outbox_events, :outbox_payload_must_be_an_object))

    drop_if_exists(constraint(:outbox_events, :outbox_classification_must_be_internal))

    drop_if_exists(constraint(:outbox_events, :outbox_schema_version_must_be_positive))

    drop_if_exists(constraint(:outbox_events, :outbox_event_type_must_not_be_empty))

    drop_if_exists(constraint(:outbox_events, :outbox_aggregate_type_must_not_be_empty))

    drop(constraint(:outbox_events, "outbox_events_aggregate_tenant_fkey"))

    drop(constraint(:outbox_events, "outbox_events_actor_tenant_fkey"))

    drop(constraint(:outbox_events, "outbox_events_tenant_id_fkey"))

    alter table(:outbox_events) do
      modify(:tenant_id, :uuid)
    end

    drop_if_exists(
      index(:foundation_records, [:tenant_id, :audit_reference],
        name: "foundation_records_tenant_id_audit_reference_index"
      )
    )

    drop_if_exists(constraint(:foundation_records, :submitted_record_requires_audit_reference))

    drop_if_exists(
      constraint(:foundation_records, :foundation_record_lock_version_must_be_positive)
    )

    drop_if_exists(constraint(:foundation_records, :foundation_record_status_must_be_known))

    drop_if_exists(constraint(:foundation_records, :name_must_not_be_empty))

    drop(constraint(:foundation_records, "foundation_records_tenant_id_fkey"))

    alter table(:foundation_records) do
      modify(:tenant_id, :uuid)
    end

    drop_if_exists(constraint(:actors, :actor_kind_must_be_known))

    drop_if_exists(constraint(:actors, :actor_name_must_not_be_empty))

    drop(constraint(:actors, "actors_tenant_id_fkey"))

    alter table(:actors) do
      modify(:tenant_id, :uuid)
    end

    drop(table(:tenants))

    drop_if_exists(
      index(:outbox_events, [:tenant_id, :aggregate_type, :aggregate_id],
        name: "outbox_events_tenant_id_aggregate_type_aggregate_id_index"
      )
    )

    drop_if_exists(
      index(:outbox_events, [:tenant_id, :occurred_at, :id],
        name: "outbox_events_tenant_id_occurred_at_id_index"
      )
    )

    drop_if_exists(
      index(:outbox_events, [:tenant_id, :audit_reference],
        name: "outbox_events_tenant_id_audit_reference_index"
      )
    )

    drop(table(:outbox_events))

    drop_if_exists(
      index(:foundation_records, [:id, :tenant_id], name: "foundation_records_id_tenant_id_index")
    )

    drop_if_exists(
      index(:foundation_records, [:tenant_id], name: "foundation_records_tenant_id_index")
    )

    drop(table(:foundation_records))

    drop_if_exists(index(:actors, [:id, :tenant_id], name: "actors_id_tenant_id_index"))

    drop_if_exists(index(:actors, [:tenant_id], name: "actors_tenant_id_index"))

    drop(table(:actors))
  end
end
