defmodule AshFoundationLab.Repo.Migrations.Phase0GeneratedIdempotencyReview do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:action_idempotency_keys, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "action_idempotency_keys_tenant_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ), null: false)

      add(
        :actor_id,
        references(:actors,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "action_idempotency_keys_actor_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ), null: false)

      add(:action_name, :text, null: false)
      add(:idempotency_key, :uuid, null: false)
      add(:aggregate_type, :text, null: false)

      add(
        :aggregate_id,
        references(:foundation_records,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "action_idempotency_keys_aggregate_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ), null: false)

      add(:request_hash, :binary, null: false)
      add(:status, :text, null: false, default: "started")
      add(:result_lock_version, :bigint)
      add(:result_audit_reference, :uuid)
      add(:completed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:action_idempotency_keys, :action_idempotency_action_name_must_not_be_empty,
             check: """
               char_length(action_name) > 0
             """
           )

    create constraint(
             :action_idempotency_keys,
             :action_idempotency_aggregate_type_must_not_be_empty,
             check: """
               char_length(aggregate_type) > 0
             """
           )

    create constraint(:action_idempotency_keys, :action_idempotency_request_hash_must_be_sha256,
             check: """
               octet_length(request_hash) = 32
             """
           )

    create constraint(:action_idempotency_keys, :action_idempotency_status_must_be_known,
             check: """
               status IN ('started', 'completed')
             """
           )

    create constraint(:action_idempotency_keys, :action_idempotency_completion_must_be_consistent,
             check: """
               (status = 'started' AND result_lock_version IS NULL AND
               result_audit_reference IS NULL AND completed_at IS NULL) OR
             (status = 'completed' AND result_lock_version IS NOT NULL AND
               result_audit_reference IS NOT NULL AND completed_at IS NOT NULL)

             """
           )

    create constraint(
             :action_idempotency_keys,
             :action_idempotency_result_lock_version_must_be_positive,
             check: """
               result_lock_version IS NULL OR result_lock_version >= 1
             """
           )

    create index(:action_idempotency_keys, [:tenant_id, :action_name, :idempotency_key],
             name: "action_idempotency_keys_tenant_action_key_index",
             unique: true
           )

    create index(:action_idempotency_keys, [:tenant_id, :inserted_at, :id],
             name: "action_idempotency_keys_tenant_inserted_id_index"
           )

    create index(:action_idempotency_keys, [:tenant_id, :aggregate_type, :aggregate_id],
             name: "action_idempotency_keys_tenant_aggregate_index"
           )
  end

  def down do
    drop_if_exists(
      index(:action_idempotency_keys, [:tenant_id, :aggregate_type, :aggregate_id],
        name: "action_idempotency_keys_tenant_aggregate_index"
      )
    )

    drop_if_exists(
      index(:action_idempotency_keys, [:tenant_id, :inserted_at, :id],
        name: "action_idempotency_keys_tenant_inserted_id_index"
      )
    )

    drop_if_exists(
      index(:action_idempotency_keys, [:tenant_id, :action_name, :idempotency_key],
        name: "action_idempotency_keys_tenant_action_key_index"
      )
    )

    drop_if_exists(
      constraint(
        :action_idempotency_keys,
        :action_idempotency_result_lock_version_must_be_positive
      )
    )

    drop_if_exists(
      constraint(:action_idempotency_keys, :action_idempotency_completion_must_be_consistent)
    )

    drop_if_exists(constraint(:action_idempotency_keys, :action_idempotency_status_must_be_known))

    drop_if_exists(
      constraint(:action_idempotency_keys, :action_idempotency_request_hash_must_be_sha256)
    )

    drop_if_exists(
      constraint(:action_idempotency_keys, :action_idempotency_aggregate_type_must_not_be_empty)
    )

    drop_if_exists(
      constraint(:action_idempotency_keys, :action_idempotency_action_name_must_not_be_empty)
    )

    drop(constraint(:action_idempotency_keys, "action_idempotency_keys_aggregate_tenant_fkey"))

    drop(constraint(:action_idempotency_keys, "action_idempotency_keys_actor_tenant_fkey"))

    drop(constraint(:action_idempotency_keys, "action_idempotency_keys_tenant_id_fkey"))

    drop(table(:action_idempotency_keys))
  end
end
