defmodule Chimwemwe.Repo.Migrations.ProviderNeutralIdentityConnection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      constraint(:identity_sso_connections, :identity_sso_connections_provider_allowed)
    )

    rename(table(:identity_sso_connections), :provider, to: :protocol)

    execute(
      "UPDATE identity_sso_connections SET protocol = 'oidc' WHERE protocol IN ('google', 'microsoft')"
    )

    create constraint(:identity_sso_connections, :identity_sso_connections_protocol_allowed,
             check: """
               protocol IN ('oidc', 'saml')
             """
           )
  end

  def down do
    drop_if_exists(
      constraint(:identity_sso_connections, :identity_sso_connections_protocol_allowed)
    )

    rename(table(:identity_sso_connections), :protocol, to: :provider)

    create constraint(:identity_sso_connections, :identity_sso_connections_provider_allowed,
             check: """
               provider IN ('google', 'microsoft', 'oidc', 'saml')
             """
           )
  end
end
