defmodule Chimwemwe.Repo.Migrations.AddInstitutionalFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and manually reordered so tenant-qualified destination indexes exist before
  their dependent compound foreign keys.
  """

  use Ecto.Migration

  def up do
    create table(:academic_calendars, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :institutional_unit_id,
        references(:institutional_units,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "academic_calendars_institutional_unit_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:code, :text, null: false)
      add(:status, :text, null: false, default: "active")
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:academic_calendars, :academic_calendars_code,
             check: """
               code ~ '^[a-z][a-z0-9_]{0,79}$'
             """
           )

    create constraint(:academic_calendars, :academic_calendars_status,
             check: """
               status = 'active'
             """
           )

    create constraint(:academic_calendars, :academic_calendars_lock_version,
             check: """
               lock_version >= 1
             """
           )

    create index(:academic_calendars, [:id, :tenant_id],
             name: "academic_calendars_id_tenant_idx",
             unique: true
           )

    create index(:academic_calendars, [:tenant_id, :institutional_unit_id, :code],
             name: "academic_calendars_owner_code_idx",
             unique: true
           )

    create table(:academic_years, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :calendar_id,
        references(:academic_calendars,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "academic_years_calendar_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:code, :text, null: false)
      add(:label, :text, null: false)
      add(:start_on, :date, null: false)
      add(:end_on, :date, null: false)
      add(:time_zone, :text, null: false)
      add(:instructional_weekdays, {:array, :bigint}, null: false)
      add(:candidate_revision, :text, null: false)
      add(:status, :text, null: false, default: "draft")
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:academic_years, :academic_years_code,
             check: """
               code ~ '^[a-z][a-z0-9_]{0,79}$'
             """
           )

    create constraint(:academic_years, :academic_years_label,
             check: """
               char_length(btrim(label)) BETWEEN 1 AND 160
             """
           )

    create constraint(:academic_years, :academic_years_date_range,
             check: """
               end_on >= start_on AND (end_on - start_on) < 731
             """
           )

    create constraint(:academic_years, :academic_years_time_zone,
             check: """
               char_length(time_zone) BETWEEN 3 AND 80
             """
           )

    create constraint(:academic_years, :academic_years_instructional_weekdays,
             check: """
               cardinality(instructional_weekdays) BETWEEN 1 AND 7
             """
           )

    create constraint(:academic_years, :academic_years_candidate_revision,
             check: """
               candidate_revision ~ '^[0-9a-f]{64}$'
             """
           )

    create constraint(:academic_years, :academic_years_status,
             check: """
               status IN ('draft', 'published')
             """
           )

    create constraint(:academic_years, :academic_years_lock_version,
             check: """
               lock_version >= 1
             """
           )

    create index(:academic_years, [:id, :tenant_id],
             name: "academic_years_id_tenant_idx",
             unique: true
           )

    create index(:academic_years, [:id, :tenant_id, :calendar_id],
             name: "academic_years_identity_calendar_idx",
             unique: true
           )

    create index(:academic_years, [:tenant_id, :calendar_id, :code],
             name: "academic_years_calendar_code_idx",
             unique: true
           )

    create table(:academic_periods, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :academic_year_id,
        references(:academic_years,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "academic_periods_year_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:period_type_key, :text, null: false)
      add(:label, :text, null: false)
      add(:sequence, :bigint, null: false)
      add(:start_on, :date, null: false)
      add(:end_on, :date, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:academic_periods, :academic_periods_type_key,
             check: """
               period_type_key ~ '^[a-z][a-z0-9_]{0,79}$'
             """
           )

    create constraint(:academic_periods, :academic_periods_label,
             check: """
               char_length(btrim(label)) BETWEEN 1 AND 160
             """
           )

    create constraint(:academic_periods, :academic_periods_sequence,
             check: """
               sequence >= 1
             """
           )

    create constraint(:academic_periods, :academic_periods_date_range,
             check: """
               end_on >= start_on
             """
           )

    create index(:academic_periods, [:id, :tenant_id],
             name: "academic_periods_id_tenant_idx",
             unique: true
           )

    create index(:academic_periods, [:tenant_id, :academic_year_id, :sequence],
             name: "academic_periods_year_sequence_idx",
             unique: true
           )

    create index(:academic_periods, [:tenant_id, :academic_year_id, :start_on, :end_on],
             name: "academic_periods_year_dates_idx"
           )

    create table(:academic_calendar_closures, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :academic_year_id,
        references(:academic_years,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "academic_calendar_closures_year_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:date, :date, null: false)
      add(:reason_key, :text, null: false)
      add(:label, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:academic_calendar_closures, :academic_calendar_closures_reason_key,
             check: """
               reason_key ~ '^[a-z][a-z0-9_]{0,79}$'
             """
           )

    create constraint(:academic_calendar_closures, :academic_calendar_closures_label,
             check: """
               char_length(btrim(label)) BETWEEN 1 AND 160
             """
           )

    create index(:academic_calendar_closures, [:id, :tenant_id],
             name: "academic_calendar_closures_id_tenant_idx",
             unique: true
           )

    create index(:academic_calendar_closures, [:tenant_id, :academic_year_id, :date],
             name: "academic_calendar_closures_year_date_idx",
             unique: true
           )
  end

  def down do
    execute("""
    DO $$
    BEGIN
      IF EXISTS (SELECT 1 FROM academic_calendar_closures)
         OR EXISTS (SELECT 1 FROM academic_periods)
         OR EXISTS (SELECT 1 FROM academic_years)
         OR EXISTS (SELECT 1 FROM academic_calendars)
      THEN
        RAISE EXCEPTION 'academic calendar rollback requires empty state';
      END IF;
    END
    $$;
    """)

    drop(table(:academic_calendar_closures))
    drop(table(:academic_periods))
    drop(table(:academic_years))
    drop(table(:academic_calendars))
  end
end
