defmodule Chimwemwe.Repo.Migrations.RestrictPeopleOutboxStorage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      constraint(:platform_outbox_events, :platform_outbox_classification_must_be_internal)
    )

    create constraint(:platform_outbox_events, :platform_outbox_classification_domain_boundary,
             check: """
               (classification = 'internal' AND aggregate_type NOT LIKE 'people.core.%') OR (classification = 'restricted' AND aggregate_type IN ('people.core.person', 'people.core.participation', 'people.core.account') AND event_type LIKE 'people.core.%')
             """
           )
  end

  def down do
    execute("""
    DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM people_persons)
         OR EXISTS (SELECT 1 FROM platform_outbox_events WHERE classification = 'restricted')
         OR EXISTS (SELECT 1 FROM platform_authority_audit_events WHERE action_name LIKE 'people.core.%')
         OR EXISTS (SELECT 1 FROM platform_authority_action_idempotency WHERE action_name LIKE 'people.core.%') THEN
        RAISE EXCEPTION 'retained people foundation cannot be rolled back';
      END IF;
    END $$;
    """)

    drop_if_exists(
      constraint(:platform_outbox_events, :platform_outbox_classification_domain_boundary)
    )

    create constraint(:platform_outbox_events, :platform_outbox_classification_must_be_internal,
             check: """
               classification = 'internal'
             """
           )
  end
end
