defmodule Chimwemwe.Repo.Migrations.AddLocalAccountLifecycle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:identity_accounts) do
      add(:actor_id, :uuid)
      add(:temporary_password_expires_at, :utc_datetime_usec)
      add(:password_changed_at, :utc_datetime_usec)
      add(:failed_attempt_count, :bigint, null: false, default: 0)
      add(:locked_until, :utc_datetime_usec)
      add(:lock_version, :bigint, null: false, default: 1)
    end

    execute("UPDATE identity_accounts SET actor_id = gen_random_uuid() WHERE actor_id IS NULL")

    alter table(:identity_accounts) do
      modify(:actor_id, :uuid, null: false)
    end

    execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT lower(btrim(email))
        FROM identity_accounts
        GROUP BY lower(btrim(email))
        HAVING count(*) > 1
      ) THEN
        RAISE EXCEPTION 'identity account emails conflict after normalization';
      END IF;
    END
    $$
    """)

    execute("UPDATE identity_accounts SET email = lower(btrim(email))")

    create unique_index(:identity_accounts, [:actor_id],
             name: "identity_accounts_unique_actor_index"
           )

    alter table(:identity_accounts) do
      modify(:status, :text, default: "pending_first_login")
    end

    drop_if_exists(constraint(:identity_accounts, :identity_accounts_status_allowed))

    create constraint(:identity_accounts, :identity_accounts_status_allowed,
             check: """
               status IN ('pending_first_login', 'active', 'suspended')
             """
           )

    create constraint(:identity_accounts, :identity_accounts_temporary_state,
             check: """
               (status = 'pending_first_login' AND temporary_password_expires_at IS NOT NULL) OR (status <> 'pending_first_login' AND temporary_password_expires_at IS NULL)
             """
           )

    create constraint(:identity_accounts, :identity_accounts_failed_attempt_count,
             check: """
               failed_attempt_count >= 0
             """
           )

    create constraint(:identity_accounts, :identity_accounts_lock_version,
             check: """
               lock_version >= 1
             """
           )

    create constraint(:identity_accounts, :identity_accounts_normalized_email,
             check: """
               email = lower(btrim(email))
             """
           )
  end

  def down do
    drop_if_exists(constraint(:identity_accounts, :identity_accounts_normalized_email))

    drop_if_exists(constraint(:identity_accounts, :identity_accounts_lock_version))

    drop_if_exists(constraint(:identity_accounts, :identity_accounts_failed_attempt_count))

    drop_if_exists(constraint(:identity_accounts, :identity_accounts_temporary_state))

    drop_if_exists(constraint(:identity_accounts, :identity_accounts_status_allowed))

    execute(
      "UPDATE identity_accounts SET status = 'suspended' WHERE status = 'pending_first_login'"
    )

    create constraint(:identity_accounts, :identity_accounts_status_allowed,
             check: """
               status IN ('active', 'suspended')
             """
           )

    alter table(:identity_accounts) do
      modify(:status, :text, default: "active")
    end

    drop_if_exists(
      unique_index(:identity_accounts, [:actor_id], name: "identity_accounts_unique_actor_index")
    )

    alter table(:identity_accounts) do
      remove(:lock_version)
      remove(:locked_until)
      remove(:failed_attempt_count)
      remove(:password_changed_at)
      remove(:temporary_password_expires_at)
      remove(:actor_id)
    end
  end
end
