defmodule Chimwemwe.Repo.Migrations.AddAttendanceCorrections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create(
      index(:classroom_attendance_submissions, [:id, :tenant_id],
        name: "classroom_attendance_submissions_id_tenant_idx",
        unique: true
      )
    )

    create table(:classroom_attendance_corrections, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :submission_id,
        references(:classroom_attendance_submissions,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "classroom_attendance_correction_submission_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:previous_correction_id, :uuid)

      add(:correction_number, :bigint, null: false)
      add(:reason_code, :text, null: false)
      add(:marks, :map, null: false)
      add(:recorded_at, :utc_datetime_usec, null: false)
    end

    create(
      constraint(
        :classroom_attendance_corrections,
        :classroom_attendance_correction_predecessor_shape,
        check: """
          (correction_number = 1 AND previous_correction_id IS NULL) OR
        (correction_number BETWEEN 2 AND 10 AND previous_correction_id IS NOT NULL)

        """
      )
    )

    create(
      constraint(:classroom_attendance_corrections, :classroom_attendance_correction_reason,
        check: """
          reason_code = 'marking_error'
        """
      )
    )

    create(
      constraint(:classroom_attendance_corrections, :classroom_attendance_correction_marks,
        check: """
          jsonb_typeof(marks) = 'object'
        """
      )
    )

    create(
      index(:classroom_attendance_corrections, [:id, :tenant_id],
        name: "classroom_attendance_corrections_id_tenant_idx",
        unique: true
      )
    )

    create(
      index(:classroom_attendance_corrections, [:id, :tenant_id, :submission_id],
        name: "classroom_attendance_corrections_submission_idx",
        unique: true
      )
    )

    create(
      index(
        :classroom_attendance_corrections,
        [:tenant_id, :submission_id, :correction_number],
        name: "classroom_attendance_correction_number_idx",
        unique: true
      )
    )

    create(
      index(
        :classroom_attendance_corrections,
        [:tenant_id, :submission_id, :recorded_at, :id],
        name: "classroom_attendance_correction_history_idx"
      )
    )

    execute("""
    ALTER TABLE classroom_attendance_corrections
    ADD CONSTRAINT classroom_attendance_correction_predecessor_fkey
    FOREIGN KEY (previous_correction_id, tenant_id, submission_id)
    REFERENCES classroom_attendance_corrections (id, tenant_id, submission_id)
    MATCH SIMPLE
    ON DELETE RESTRICT;
    """)

    execute("""
    CREATE FUNCTION guard_classroom_attendance_correction()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
          CONSTRAINT = 'classroom_attendance_correction_delete_forbidden',
          MESSAGE = 'attendance correction deletion is forbidden';
      END IF;

      IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
          CONSTRAINT = 'classroom_attendance_correction_immutable',
          MESSAGE = 'attendance corrections are immutable';
      END IF;

      PERFORM pg_advisory_xact_lock(
        hashtextextended(
          'classroom-attendance-correction:' ||
            NEW.tenant_id::text || ':' || NEW.submission_id::text,
          0
        )
      );

      NEW.recorded_at := transaction_timestamp() AT TIME ZONE 'UTC';

      IF NEW.correction_number = 1 THEN
        IF EXISTS (
          SELECT 1 FROM classroom_attendance_corrections
          WHERE tenant_id = NEW.tenant_id AND submission_id = NEW.submission_id
        ) THEN
          RAISE EXCEPTION USING ERRCODE = '23514',
            CONSTRAINT = 'classroom_attendance_correction_chain',
            MESSAGE = 'attendance correction baseline already exists';
        END IF;
      ELSIF NOT EXISTS (
        SELECT 1 FROM classroom_attendance_corrections
        WHERE id = NEW.previous_correction_id
          AND tenant_id = NEW.tenant_id
          AND submission_id = NEW.submission_id
          AND correction_number = NEW.correction_number - 1
      ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
          CONSTRAINT = 'classroom_attendance_correction_chain',
          MESSAGE = 'attendance correction predecessor is not consecutive';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER classroom_attendance_correction_guard
    BEFORE INSERT OR UPDATE OR DELETE ON classroom_attendance_corrections
    FOR EACH ROW EXECUTE FUNCTION guard_classroom_attendance_correction();
    """)

    drop_if_exists(
      constraint(:platform_outbox_events, :platform_outbox_classification_domain_boundary)
    )

    create(
      constraint(:platform_outbox_events, :platform_outbox_classification_domain_boundary,
        check: """
          (classification = 'internal' AND aggregate_type NOT LIKE 'people.core.%' AND aggregate_type NOT LIKE 'classroom.core.%' AND aggregate_type NOT LIKE 'classroom.attendance.%') OR (classification = 'restricted' AND aggregate_type IN ('people.core.person', 'people.core.participation', 'people.core.account') AND event_type LIKE 'people.core.%') OR (classification = 'restricted' AND aggregate_type IN ('classroom.core.class', 'classroom.core.enrolment', 'classroom.core.assignment', 'classroom.core.placement') AND event_type LIKE 'classroom.core.%') OR (classification = 'restricted' AND aggregate_type = 'classroom.attendance.submission' AND event_type IN ('classroom.attendance.submit.completed', 'classroom.attendance.correct.completed'))
        """
      )
    )
  end

  def down do
    execute("""
    DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM classroom_attendance_corrections)
        OR EXISTS (SELECT 1 FROM platform_outbox_events WHERE event_type = 'classroom.attendance.correct.completed')
        OR EXISTS (SELECT 1 FROM platform_authority_audit_events WHERE action_name = 'classroom.attendance.correct')
        OR EXISTS (SELECT 1 FROM platform_authority_action_idempotency WHERE action_name = 'classroom.attendance.correct') THEN
        RAISE EXCEPTION 'retained attendance correction evidence requires forward repair';
      END IF;
    END $$;
    """)

    drop_if_exists(
      constraint(:platform_outbox_events, :platform_outbox_classification_domain_boundary)
    )

    create(
      constraint(:platform_outbox_events, :platform_outbox_classification_domain_boundary,
        check: """
          (classification = 'internal' AND aggregate_type NOT LIKE 'people.core.%' AND aggregate_type NOT LIKE 'classroom.core.%' AND aggregate_type NOT LIKE 'classroom.attendance.%') OR (classification = 'restricted' AND aggregate_type IN ('people.core.person', 'people.core.participation', 'people.core.account') AND event_type LIKE 'people.core.%') OR (classification = 'restricted' AND aggregate_type IN ('classroom.core.class', 'classroom.core.enrolment', 'classroom.core.assignment', 'classroom.core.placement') AND event_type LIKE 'classroom.core.%') OR (classification = 'restricted' AND aggregate_type = 'classroom.attendance.submission' AND event_type = 'classroom.attendance.submit.completed')
        """
      )
    )

    execute("""
    DROP TRIGGER classroom_attendance_correction_guard ON classroom_attendance_corrections;
    """)

    execute("""
    DROP FUNCTION guard_classroom_attendance_correction();
    """)

    drop(
      constraint(
        :classroom_attendance_corrections,
        "classroom_attendance_correction_predecessor_fkey"
      )
    )

    drop_if_exists(
      index(:classroom_attendance_corrections, [:tenant_id, :submission_id, :recorded_at, :id],
        name: "classroom_attendance_correction_history_idx"
      )
    )

    drop_if_exists(
      index(:classroom_attendance_corrections, [:tenant_id, :submission_id, :correction_number],
        name: "classroom_attendance_correction_number_idx"
      )
    )

    drop_if_exists(
      index(:classroom_attendance_corrections, [:id, :tenant_id, :submission_id],
        name: "classroom_attendance_corrections_submission_idx"
      )
    )

    drop_if_exists(
      index(:classroom_attendance_corrections, [:id, :tenant_id],
        name: "classroom_attendance_corrections_id_tenant_idx"
      )
    )

    drop_if_exists(
      constraint(:classroom_attendance_corrections, :classroom_attendance_correction_marks)
    )

    drop_if_exists(
      constraint(:classroom_attendance_corrections, :classroom_attendance_correction_reason)
    )

    drop_if_exists(
      constraint(
        :classroom_attendance_corrections,
        :classroom_attendance_correction_predecessor_shape
      )
    )

    drop(
      constraint(
        :classroom_attendance_corrections,
        "classroom_attendance_correction_submission_fkey"
      )
    )

    drop(table(:classroom_attendance_corrections))

    drop_if_exists(
      index(:classroom_attendance_submissions, [:id, :tenant_id],
        name: "classroom_attendance_submissions_id_tenant_idx"
      )
    )
  end
end
