defmodule Chimwemwe.Repo.Migrations.Phase2TemporalControlGuard do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE FUNCTION guard_platform_temporal_retention_control()
    RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE
      receipt_operation text;
      receipt_version bigint;
      receipt_hold_digest bytea;
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_retention_control_delete_forbidden',
          MESSAGE = 'temporal retention control deletion is forbidden';
      END IF;

      IF TG_OP = 'UPDATE' THEN
        IF NEW.id <> OLD.id
           OR NEW.tenant_id <> OLD.tenant_id
           OR NEW.aggregate_id <> OLD.aggregate_id
           OR NEW.scope_id <> OLD.scope_id
           OR NEW.module_key <> OLD.module_key
           OR NEW.policy_key <> OLD.policy_key
           OR NEW.classification <> OLD.classification
           OR NEW.retention_started_on <> OLD.retention_started_on
           OR NEW.retain_until <> OLD.retain_until
           OR NEW.inserted_at <> OLD.inserted_at
           OR NEW.version <> OLD.version + 1 THEN
          RAISE EXCEPTION USING ERRCODE = '23514',
            CONSTRAINT = 'platform_temporal_retention_control_transition_invalid',
            MESSAGE = 'temporal retention control transition is invalid';
        END IF;

        SELECT operation, version, hold_reference_digest
        INTO receipt_operation, receipt_version, receipt_hold_digest
        FROM platform_temporal_qualification_retention_receipts
        WHERE id = NEW.current_receipt_id
          AND tenant_id = NEW.tenant_id
          AND control_id = NEW.id
          AND aggregate_id = NEW.aggregate_id;

        IF receipt_version IS DISTINCT FROM NEW.version OR NOT (
          (OLD.state = 'retained' AND NEW.state = 'held'
            AND receipt_operation = 'hold_placed'
            AND NEW.active_hold_digest = receipt_hold_digest
            AND NEW.erased_at IS NULL)
          OR
          (OLD.state = 'held' AND NEW.state = 'retained'
            AND receipt_operation = 'hold_released'
            AND receipt_hold_digest = OLD.active_hold_digest
            AND NEW.active_hold_digest IS NULL
            AND NEW.erased_at IS NULL)
          OR
          (OLD.state = 'retained' AND NEW.state = 'erased'
            AND receipt_operation = 'erased'
            AND NEW.active_hold_digest IS NULL
            AND NEW.retain_until <= CURRENT_DATE
            AND NEW.erased_at IS NOT NULL)
        ) THEN
          RAISE EXCEPTION USING ERRCODE = '23514',
            CONSTRAINT = 'platform_temporal_retention_control_transition_invalid',
            MESSAGE = 'temporal retention control transition is invalid';
        END IF;

        NEW.updated_at := transaction_timestamp() AT TIME ZONE 'UTC';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER platform_temporal_retention_control_guard
    BEFORE UPDATE OR DELETE ON platform_temporal_qualification_retention_controls
    FOR EACH ROW EXECUTE FUNCTION guard_platform_temporal_retention_control();
    """)
  end

  def down do
    execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM platform_temporal_qualification_retention_controls LIMIT 1
      ) OR EXISTS (
        SELECT 1 FROM platform_temporal_qualification_retention_receipts LIMIT 1
      ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
          MESSAGE = 'cannot remove temporal retention guards while retained evidence exists';
      END IF;
    END;
    $$;
    """)

    execute("""
    DROP TRIGGER platform_temporal_retention_control_guard ON platform_temporal_qualification_retention_controls;
    """)

    execute("""
    DROP FUNCTION guard_platform_temporal_retention_control();
    """)
  end
end
