defmodule Chimwemwe.Repo.Migrations.ConstrainPhase2IdentityLinkFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:identity_external_identity_links) do
      modify(
        :connection_id,
        references(:identity_connections,
          column: :id,
          match: :simple,
          name: "identity_external_identity_links_connection_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    alter table(:identity_invitations) do
      modify(
        :membership_id,
        references(:platform_tenant_memberships,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "identity_invitations_membership_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )

      modify(
        :role_id,
        references(:platform_roles,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "identity_invitations_role_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )

      modify(
        :connection_id,
        references(:identity_connections,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "identity_invitations_connection_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )

      modify(
        :external_identity_link_id,
        references(:identity_external_identity_links,
          column: :id,
          match: :simple,
          name: "identity_invitations_external_link_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    drop_if_exists(
      index(:identity_invitations, [:tenant_id, :token_digest],
        name: "identity_invitations_token_digest_index"
      )
    )

    create index(:identity_invitations, [:token_digest],
             name: "identity_invitations_token_digest_index",
             unique: true
           )
  end

  def down do
    drop_if_exists(
      index(:identity_invitations, [:token_digest],
        name: "identity_invitations_token_digest_index"
      )
    )

    create index(:identity_invitations, [:tenant_id, :token_digest],
             name: "identity_invitations_token_digest_index",
             unique: true
           )

    drop(constraint(:identity_invitations, "identity_invitations_external_link_fkey"))

    drop(constraint(:identity_invitations, "identity_invitations_connection_tenant_fkey"))

    drop(constraint(:identity_invitations, "identity_invitations_role_tenant_fkey"))

    drop(constraint(:identity_invitations, "identity_invitations_membership_tenant_fkey"))

    alter table(:identity_invitations) do
      modify(:external_identity_link_id, :uuid)
      modify(:connection_id, :uuid)
      modify(:role_id, :uuid)
      modify(:membership_id, :uuid)
    end

    drop(
      constraint(
        :identity_external_identity_links,
        "identity_external_identity_links_connection_fkey"
      )
    )

    alter table(:identity_external_identity_links) do
      modify(:connection_id, :uuid)
    end
  end
end
