defmodule Chimwemwe.Repo.Migrations.TemporalQualificationFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:platform_temporal_qualification_aggregates, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:scope_id, :uuid, null: false)
      add(:current_revision_id, :uuid)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create index(:platform_temporal_qualification_aggregates, [:id, :tenant_id],
             name: "platform_temporal_qualification_aggregates_id_tenant_index",
             unique: true
           )

    create index(:platform_temporal_qualification_aggregates, [:id, :tenant_id, :scope_id],
             name: "platform_temporal_qualification_aggregates_scope_index",
             unique: true
           )

    create index(:platform_temporal_qualification_aggregates, [:tenant_id, :scope_id],
             name: "platform_temporal_qualification_scope_index"
           )

    execute("""
    CREATE FUNCTION guard_platform_temporal_qualification_aggregate()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      previous_revision bigint;
      selected_revision bigint;
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_aggregate_delete_forbidden',
          MESSAGE = 'temporal qualification aggregate deletion is forbidden';
      END IF;

      IF NEW.id <> OLD.id
         OR NEW.tenant_id <> OLD.tenant_id
         OR NEW.scope_id <> OLD.scope_id
         OR NEW.inserted_at <> OLD.inserted_at THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_aggregate_identity_immutable',
          MESSAGE = 'temporal qualification aggregate identity is immutable';
      END IF;

      IF OLD.current_revision_id IS NOT NULL
         AND NEW.current_revision_id IS NULL THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_current_revision_monotonic',
          MESSAGE = 'current temporal qualification revision cannot be cleared';
      END IF;

      IF OLD.current_revision_id IS DISTINCT FROM NEW.current_revision_id
         AND OLD.current_revision_id IS NOT NULL THEN
        SELECT aggregate_revision
        INTO previous_revision
        FROM platform_temporal_qualification_revisions
        WHERE id = OLD.current_revision_id
          AND tenant_id = OLD.tenant_id
          AND aggregate_id = OLD.id;

        SELECT aggregate_revision
        INTO selected_revision
        FROM platform_temporal_qualification_revisions
        WHERE id = NEW.current_revision_id
          AND tenant_id = NEW.tenant_id
          AND aggregate_id = NEW.id;

        IF selected_revision IS NULL OR selected_revision <= previous_revision THEN
          RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'platform_temporal_qualification_current_revision_monotonic',
            MESSAGE = 'current temporal qualification revision must advance';
        END IF;
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER platform_temporal_qualification_aggregate_guard
    BEFORE UPDATE OR DELETE
    ON platform_temporal_qualification_aggregates
    FOR EACH ROW
    EXECUTE FUNCTION guard_platform_temporal_qualification_aggregate();
    """)

    create table(:platform_temporal_qualification_facts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:scope_id, :uuid, null: false)
      add(:operation_id, :uuid, null: false)
      add(:kind, :text, null: false)

      add(:reverses_fact_id, :uuid)

      add(:effective_on, :date, null: false)
      add(:quantity, :bigint, null: false)
      add(:recorded_at, :utc_datetime_usec, null: false)
    end

    create constraint(:platform_temporal_qualification_facts, :platform_temporal_fact_kind_shape,
             check: """
               (kind = 'entry' AND reverses_fact_id IS NULL) OR
             (kind = 'reversal' AND reverses_fact_id IS NOT NULL)

             """
           )

    create constraint(
             :platform_temporal_qualification_facts,
             :platform_temporal_fact_quantity_nonzero,
             check: """
               quantity <> 0
             """
           )

    create index(:platform_temporal_qualification_facts, [:id, :tenant_id],
             name: "platform_temporal_qualification_facts_id_tenant_index",
             unique: true
           )

    create index(:platform_temporal_qualification_facts, [:id, :tenant_id, :scope_id],
             name: "platform_temporal_qualification_facts_scope_index",
             unique: true
           )

    create index(
             :platform_temporal_qualification_facts,
             [:tenant_id, :scope_id, :recorded_at, :id],
             name: "platform_temporal_qualification_fact_history_index"
           )

    create index(:platform_temporal_qualification_facts, [:tenant_id, :operation_id],
             name: "platform_temporal_qualification_fact_operation_index"
           )

    create index(:platform_temporal_qualification_facts, [:tenant_id, :reverses_fact_id],
             name: "platform_temporal_qualification_fact_reversal_index",
             unique: true,
             where: "kind = 'reversal'"
           )

    execute("""
    CREATE FUNCTION guard_platform_temporal_qualification_fact()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_fact_delete_forbidden',
          MESSAGE = 'temporal qualification fact deletion is forbidden';
      END IF;

      IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_fact_immutable',
          MESSAGE = 'temporal qualification facts are immutable';
      END IF;

      NEW.recorded_at := transaction_timestamp() AT TIME ZONE 'UTC';

      IF NEW.kind = 'reversal' AND NOT EXISTS (
        SELECT 1
        FROM platform_temporal_qualification_facts
        WHERE id = NEW.reverses_fact_id
          AND tenant_id = NEW.tenant_id
          AND scope_id = NEW.scope_id
          AND kind = 'entry'
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_fact_reversal_target',
          MESSAGE = 'temporal qualification reversal target is invalid';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER platform_temporal_qualification_fact_guard
    BEFORE INSERT OR UPDATE OR DELETE
    ON platform_temporal_qualification_facts
    FOR EACH ROW
    EXECUTE FUNCTION guard_platform_temporal_qualification_fact();
    """)

    create table(:platform_temporal_qualification_revisions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :aggregate_id,
        references(:platform_temporal_qualification_aggregates,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "platform_temporal_revision_aggregate_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:operation_id, :uuid, null: false)
      add(:aggregate_revision, :bigint, null: false)

      add(:predecessor_revision_id, :uuid)

      add(:reason_code, :text, null: false)
      add(:recorded_at, :utc_datetime_usec, null: false)
    end

    create constraint(
             :platform_temporal_qualification_revisions,
             :platform_temporal_revision_predecessor_shape,
             check: """
               (aggregate_revision = 1 AND predecessor_revision_id IS NULL) OR
             (aggregate_revision > 1 AND predecessor_revision_id IS NOT NULL)

             """
           )

    create constraint(
             :platform_temporal_qualification_revisions,
             :platform_temporal_revision_number_positive,
             check: """
               aggregate_revision >= 1
             """
           )

    create constraint(
             :platform_temporal_qualification_revisions,
             :platform_temporal_revision_reason_not_empty,
             check: """
               char_length(reason_code) BETWEEN 1 AND 80
             """
           )

    create index(:platform_temporal_qualification_revisions, [:id, :tenant_id],
             name: "platform_temporal_qualification_revisions_id_tenant_index",
             unique: true
           )

    create index(:platform_temporal_qualification_revisions, [:id, :tenant_id, :aggregate_id],
             name: "platform_temporal_qualification_revisions_aggregate_index",
             unique: true
           )

    create index(
             :platform_temporal_qualification_revisions,
             [:tenant_id, :aggregate_id, :aggregate_revision],
             name: "platform_temporal_qualification_revision_number_index",
             unique: true
           )

    create index(:platform_temporal_qualification_revisions, [:tenant_id, :operation_id],
             name: "platform_temporal_qualification_revision_operation_index",
             unique: true
           )

    create index(
             :platform_temporal_qualification_revisions,
             [:tenant_id, :aggregate_id, :recorded_at, :id],
             name: "platform_temporal_qualification_revision_history_index"
           )

    execute("""
    ALTER TABLE platform_temporal_qualification_aggregates
    ADD CONSTRAINT platform_temporal_aggregate_current_revision_fkey
    FOREIGN KEY (current_revision_id, tenant_id, id)
    REFERENCES platform_temporal_qualification_revisions (id, tenant_id, aggregate_id)
    MATCH SIMPLE
    ON DELETE RESTRICT;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_revisions
    ADD CONSTRAINT platform_temporal_revision_predecessor_tenant_fkey
    FOREIGN KEY (predecessor_revision_id, tenant_id, aggregate_id)
    REFERENCES platform_temporal_qualification_revisions (id, tenant_id, aggregate_id)
    MATCH SIMPLE
    ON DELETE RESTRICT;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_facts
    ADD CONSTRAINT platform_temporal_fact_reversal_tenant_fkey
    FOREIGN KEY (reverses_fact_id, tenant_id, scope_id)
    REFERENCES platform_temporal_qualification_facts (id, tenant_id, scope_id)
    MATCH SIMPLE
    ON DELETE RESTRICT;
    """)

    execute("""
    CREATE FUNCTION guard_platform_temporal_qualification_revision()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_revision_delete_forbidden',
          MESSAGE = 'temporal qualification revision deletion is forbidden';
      END IF;

      IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_revision_immutable',
          MESSAGE = 'temporal qualification revisions are immutable';
      END IF;

      PERFORM pg_advisory_xact_lock(
        hashtextextended(
          'platform-temporal-qualification-revision:' ||
            NEW.tenant_id::text || ':' || NEW.aggregate_id::text,
          0
        )
      );

      NEW.recorded_at := transaction_timestamp() AT TIME ZONE 'UTC';

      IF NEW.aggregate_revision = 1 THEN
        IF EXISTS (
          SELECT 1
          FROM platform_temporal_qualification_revisions
          WHERE tenant_id = NEW.tenant_id
            AND aggregate_id = NEW.aggregate_id
        ) THEN
          RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'platform_temporal_qualification_revision_chain',
            MESSAGE = 'temporal qualification baseline revision already exists';
        END IF;
      ELSIF NOT EXISTS (
        SELECT 1
        FROM platform_temporal_qualification_revisions
        WHERE id = NEW.predecessor_revision_id
          AND tenant_id = NEW.tenant_id
          AND aggregate_id = NEW.aggregate_id
          AND aggregate_revision = NEW.aggregate_revision - 1
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_revision_chain',
          MESSAGE = 'temporal qualification predecessor is not consecutive';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER platform_temporal_qualification_revision_guard
    BEFORE INSERT OR UPDATE OR DELETE
    ON platform_temporal_qualification_revisions
    FOR EACH ROW
    EXECUTE FUNCTION guard_platform_temporal_qualification_revision();
    """)

    create table(:platform_temporal_qualification_segments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :aggregate_id,
        references(:platform_temporal_qualification_aggregates,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "platform_temporal_segment_aggregate_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:revision_id, :uuid, null: false)

      add(:effective_from, :date, null: false)
      add(:effective_until, :date, null: false)
      add(:value, :text, null: false)
    end

    create constraint(
             :platform_temporal_qualification_segments,
             :platform_temporal_segment_interval_valid,
             check: """
               effective_from < effective_until
             """
           )

    create constraint(
             :platform_temporal_qualification_segments,
             :platform_temporal_segment_value_not_empty,
             check: """
               char_length(value) BETWEEN 1 AND 80
             """
           )

    create index(:platform_temporal_qualification_segments, [:id, :tenant_id],
             name: "platform_temporal_qualification_segments_id_tenant_index",
             unique: true
           )

    create index(
             :platform_temporal_qualification_segments,
             [:tenant_id, :revision_id, :effective_from, :id],
             name: "platform_temporal_qualification_segment_effective_index"
           )

    execute("""
    ALTER TABLE platform_temporal_qualification_segments
    ADD CONSTRAINT platform_temporal_segment_revision_tenant_fkey
    FOREIGN KEY (revision_id, tenant_id, aggregate_id)
    REFERENCES platform_temporal_qualification_revisions (id, tenant_id, aggregate_id)
    MATCH FULL
    ON DELETE RESTRICT;
    """)

    execute("""
    CREATE FUNCTION guard_platform_temporal_qualification_segment()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_segment_delete_forbidden',
          MESSAGE = 'temporal qualification segment deletion is forbidden';
      END IF;

      IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_segment_immutable',
          MESSAGE = 'temporal qualification segments are immutable';
      END IF;

      PERFORM pg_advisory_xact_lock(
        hashtextextended(
          'platform-temporal-qualification-segment:' ||
            NEW.tenant_id::text || ':' || NEW.revision_id::text,
          0
        )
      );

      IF EXISTS (
        SELECT 1
        FROM platform_temporal_qualification_segments AS segment
        WHERE segment.tenant_id = NEW.tenant_id
          AND segment.revision_id = NEW.revision_id
          AND NEW.effective_from < segment.effective_until
          AND segment.effective_from < NEW.effective_until
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23P01',
          CONSTRAINT = 'platform_temporal_qualification_segment_no_overlap',
          MESSAGE = 'temporal qualification segments overlap';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER platform_temporal_qualification_segment_guard
    BEFORE INSERT OR UPDATE OR DELETE
    ON platform_temporal_qualification_segments
    FOR EACH ROW
    EXECUTE FUNCTION guard_platform_temporal_qualification_segment();
    """)
  end

  def down do
    execute("""
    DROP TRIGGER platform_temporal_qualification_segment_guard
      ON platform_temporal_qualification_segments;
    """)

    execute("DROP FUNCTION guard_platform_temporal_qualification_segment();")

    drop_if_exists(
      index(
        :platform_temporal_qualification_segments,
        [:tenant_id, :revision_id, :effective_from, :id],
        name: "platform_temporal_qualification_segment_effective_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_segments, [:id, :tenant_id],
        name: "platform_temporal_qualification_segments_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_segments,
        :platform_temporal_segment_value_not_empty
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_segments,
        :platform_temporal_segment_interval_valid
      )
    )

    drop(
      constraint(
        :platform_temporal_qualification_segments,
        "platform_temporal_segment_revision_tenant_fkey"
      )
    )

    drop(
      constraint(
        :platform_temporal_qualification_segments,
        "platform_temporal_segment_aggregate_tenant_fkey"
      )
    )

    drop(table(:platform_temporal_qualification_segments))

    drop(
      constraint(
        :platform_temporal_qualification_aggregates,
        "platform_temporal_aggregate_current_revision_fkey"
      )
    )

    drop(
      constraint(
        :platform_temporal_qualification_revisions,
        "platform_temporal_revision_predecessor_tenant_fkey"
      )
    )

    execute("""
    DROP TRIGGER platform_temporal_qualification_revision_guard
      ON platform_temporal_qualification_revisions;
    """)

    execute("DROP FUNCTION guard_platform_temporal_qualification_revision();")

    drop_if_exists(
      index(
        :platform_temporal_qualification_revisions,
        [:tenant_id, :aggregate_id, :recorded_at, :id],
        name: "platform_temporal_qualification_revision_history_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_revisions, [:tenant_id, :operation_id],
        name: "platform_temporal_qualification_revision_operation_index"
      )
    )

    drop_if_exists(
      index(
        :platform_temporal_qualification_revisions,
        [:tenant_id, :aggregate_id, :aggregate_revision],
        name: "platform_temporal_qualification_revision_number_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_revisions, [:id, :tenant_id, :aggregate_id],
        name: "platform_temporal_qualification_revisions_aggregate_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_revisions, [:id, :tenant_id],
        name: "platform_temporal_qualification_revisions_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_revisions,
        :platform_temporal_revision_reason_not_empty
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_revisions,
        :platform_temporal_revision_number_positive
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_revisions,
        :platform_temporal_revision_predecessor_shape
      )
    )

    drop(
      constraint(
        :platform_temporal_qualification_revisions,
        "platform_temporal_revision_aggregate_tenant_fkey"
      )
    )

    drop(table(:platform_temporal_qualification_revisions))

    drop(
      constraint(
        :platform_temporal_qualification_facts,
        "platform_temporal_fact_reversal_tenant_fkey"
      )
    )

    execute("""
    DROP TRIGGER platform_temporal_qualification_fact_guard
      ON platform_temporal_qualification_facts;
    """)

    execute("DROP FUNCTION guard_platform_temporal_qualification_fact();")

    drop_if_exists(
      index(:platform_temporal_qualification_facts, [:tenant_id, :reverses_fact_id],
        name: "platform_temporal_qualification_fact_reversal_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_facts, [:tenant_id, :operation_id],
        name: "platform_temporal_qualification_fact_operation_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_facts, [:tenant_id, :scope_id, :recorded_at, :id],
        name: "platform_temporal_qualification_fact_history_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_facts, [:id, :tenant_id, :scope_id],
        name: "platform_temporal_qualification_facts_scope_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_facts, [:id, :tenant_id],
        name: "platform_temporal_qualification_facts_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(:platform_temporal_qualification_facts, :platform_temporal_fact_quantity_nonzero)
    )

    drop_if_exists(
      constraint(:platform_temporal_qualification_facts, :platform_temporal_fact_kind_shape)
    )

    drop(table(:platform_temporal_qualification_facts))

    execute("""
    DROP TRIGGER platform_temporal_qualification_aggregate_guard
      ON platform_temporal_qualification_aggregates;
    """)

    execute("DROP FUNCTION guard_platform_temporal_qualification_aggregate();")

    drop_if_exists(
      index(:platform_temporal_qualification_aggregates, [:tenant_id, :scope_id],
        name: "platform_temporal_qualification_scope_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_aggregates, [:id, :tenant_id, :scope_id],
        name: "platform_temporal_qualification_aggregates_scope_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_aggregates, [:id, :tenant_id],
        name: "platform_temporal_qualification_aggregates_id_tenant_index"
      )
    )

    drop(table(:platform_temporal_qualification_aggregates))
  end
end
