defmodule Chimwemwe.Repo.Migrations.GovernedExtensionDefinitions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:platform_governed_extension_definitions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :module_activation_id,
        references(:platform_module_activations,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "platform_governed_extension_definitions_activation_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:definition_key, :text, null: false)
      add(:schema_key, :text, null: false)
      add(:schema_version, :bigint, null: false)
      add(:module_version, :text, null: false)
      add(:resource_ref, :text, null: false)
      add(:descriptor_revision, :text, null: false)
      add(:classification, :text, null: false)
      add(:content, :map, null: false)
      add(:lock_version, :bigint, null: false, default: 1)
      add(:created_by, :uuid, null: false)
      add(:updated_by, :uuid, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(
             :platform_governed_extension_definitions,
             :platform_extension_definition_key_must_be_valid,
             check: """
               char_length(definition_key) BETWEEN 3 AND 120 AND definition_key ~ '^[a-z][a-z0-9_]*([.][a-z][a-z0-9_]*)+$'
             """
           )

    create constraint(
             :platform_governed_extension_definitions,
             :platform_extension_schema_key_must_be_valid,
             check: """
               char_length(schema_key) BETWEEN 3 AND 120 AND schema_key ~ '^[a-z][a-z0-9_]*([.][a-z][a-z0-9_]*)+$'
             """
           )

    create constraint(
             :platform_governed_extension_definitions,
             :platform_extension_schema_version_must_be_positive,
             check: """
               schema_version >= 1
             """
           )

    create constraint(
             :platform_governed_extension_definitions,
             :platform_extension_module_version_must_be_valid,
             check: """
               char_length(module_version) BETWEEN 5 AND 80 AND module_version ~ '^[0-9]+[.][0-9]+[.][0-9]+([+-][0-9A-Za-z.-]+)?$'
             """
           )

    create constraint(
             :platform_governed_extension_definitions,
             :platform_extension_descriptor_revision_must_be_sha256,
             check: """
               descriptor_revision ~ '^sha256:[0-9a-f]{64}$'
             """
           )

    create constraint(
             :platform_governed_extension_definitions,
             :platform_extension_classification_must_be_known,
             check: """
               classification IN ('public', 'internal', 'confidential', 'restricted')
             """
           )

    create constraint(
             :platform_governed_extension_definitions,
             :platform_extension_content_must_be_an_object,
             check: """
               jsonb_typeof(content) = 'object'
             """
           )

    create constraint(
             :platform_governed_extension_definitions,
             :platform_extension_lock_version_must_be_positive,
             check: """
               lock_version >= 1
             """
           )

    create index(:platform_governed_extension_definitions, [:id, :tenant_id],
             name: "platform_governed_extension_definitions_id_tenant_index",
             unique: true
           )

    create index(
             :platform_governed_extension_definitions,
             [:tenant_id, :module_activation_id, :definition_key],
             name: "platform_governed_extension_definitions_key_index",
             unique: true
           )

    create index(
             :platform_governed_extension_definitions,
             [:tenant_id, :schema_key, :descriptor_revision],
             name: "platform_governed_extension_definitions_contract_index"
           )
  end

  def down do
    execute("""
    DO $$
    BEGIN
      IF EXISTS (SELECT 1 FROM platform_governed_extension_definitions LIMIT 1)
         OR EXISTS (
           SELECT 1 FROM platform_authority_audit_events
           WHERE action_name = 'platform.extensions.definition.publish'
           LIMIT 1
         )
         OR EXISTS (
           SELECT 1 FROM platform_outbox_events
           WHERE event_type = 'platform.extensions.definition.published'
           LIMIT 1
         )
         OR EXISTS (
           SELECT 1 FROM platform_authority_action_idempotency
           WHERE action_name = 'platform.extensions.definition.publish'
           LIMIT 1
         ) THEN
        RAISE EXCEPTION
          'governed extension rollback requires empty definitions and publication evidence';
      END IF;
    END
    $$;
    """)

    drop_if_exists(
      index(
        :platform_governed_extension_definitions,
        [:tenant_id, :schema_key, :descriptor_revision],
        name: "platform_governed_extension_definitions_contract_index"
      )
    )

    drop_if_exists(
      index(
        :platform_governed_extension_definitions,
        [:tenant_id, :module_activation_id, :definition_key],
        name: "platform_governed_extension_definitions_key_index"
      )
    )

    drop_if_exists(
      index(:platform_governed_extension_definitions, [:id, :tenant_id],
        name: "platform_governed_extension_definitions_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :platform_governed_extension_definitions,
        :platform_extension_lock_version_must_be_positive
      )
    )

    drop_if_exists(
      constraint(
        :platform_governed_extension_definitions,
        :platform_extension_content_must_be_an_object
      )
    )

    drop_if_exists(
      constraint(
        :platform_governed_extension_definitions,
        :platform_extension_classification_must_be_known
      )
    )

    drop_if_exists(
      constraint(
        :platform_governed_extension_definitions,
        :platform_extension_descriptor_revision_must_be_sha256
      )
    )

    drop_if_exists(
      constraint(
        :platform_governed_extension_definitions,
        :platform_extension_module_version_must_be_valid
      )
    )

    drop_if_exists(
      constraint(
        :platform_governed_extension_definitions,
        :platform_extension_schema_version_must_be_positive
      )
    )

    drop_if_exists(
      constraint(
        :platform_governed_extension_definitions,
        :platform_extension_schema_key_must_be_valid
      )
    )

    drop_if_exists(
      constraint(
        :platform_governed_extension_definitions,
        :platform_extension_definition_key_must_be_valid
      )
    )

    drop(
      constraint(
        :platform_governed_extension_definitions,
        "platform_governed_extension_definitions_activation_tenant_fkey"
      )
    )

    drop(table(:platform_governed_extension_definitions))
  end
end
