defmodule Chimwemwe.Repo.Migrations.CorrectPhase2SessionRotationReference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(
      constraint(:identity_application_sessions, "identity_application_sessions_rotated_to_fkey")
    )

    alter table(:identity_application_sessions) do
      modify(
        :rotated_to_session_id,
        references(:identity_application_sessions,
          column: :id,
          match: :simple,
          name: "identity_application_sessions_rotated_to_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end
  end

  def down do
    drop(
      constraint(:identity_application_sessions, "identity_application_sessions_rotated_to_fkey")
    )

    alter table(:identity_application_sessions) do
      modify(
        :rotated_to_session_id,
        references(:identity_application_sessions,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "identity_application_sessions_rotated_to_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end
  end
end
