defmodule Chimwemwe.Repo.Migrations.Phase2SupportAccessFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:identity_support_access_grants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:support_actor_id, :uuid, null: false)
      add(:grantor_actor_id, :uuid, null: false)

      add(
        :session_id,
        references(:identity_application_sessions,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "identity_support_access_grants_session_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )

      add(:purpose, :text, null: false)
      add(:ticket_reference, :text, null: false)
      add(:capability_scope, {:array, :text}, null: false)
      add(:assurance_required, :text, null: false, default: "mfa")
      add(:status, :text, null: false, default: "approved")
      add(:expires_at, :utc_datetime_usec, null: false)
      add(:activated_at, :utc_datetime_usec)
      add(:ended_at, :utc_datetime_usec)
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(
             :identity_support_access_grants,
             :identity_support_access_grants_status_allowed,
             check: """
               status IN ('approved', 'active', 'revoked', 'ended')
             """
           )

    create constraint(
             :identity_support_access_grants,
             :identity_support_access_grants_lock_version_positive,
             check: """
               lock_version >= 1
             """
           )

    create constraint(
             :identity_support_access_grants,
             :identity_support_access_grants_scope_nonempty,
             check: """
               cardinality(capability_scope) BETWEEN 1 AND 8
             """
           )

    create constraint(
             :identity_support_access_grants,
             :identity_support_access_grants_maximum_lifetime,
             check: """
               expires_at > inserted_at AND expires_at <= inserted_at + INTERVAL '60 minutes'
             """
           )

    create constraint(
             :identity_support_access_grants,
             :identity_support_access_grants_independent_approval,
             check: """
               support_actor_id <> grantor_actor_id
             """
           )

    create constraint(
             :identity_support_access_grants,
             :identity_support_access_grants_activation_consistent,
             check: """
               (status = 'approved' AND session_id IS NULL AND activated_at IS NULL) OR
             (status = 'active' AND session_id IS NOT NULL AND activated_at IS NOT NULL) OR
             (status IN ('revoked', 'ended'))

             """
           )

    create index(:identity_support_access_grants, [:id, :tenant_id],
             name: "identity_support_access_grants_id_tenant_index",
             unique: true
           )

    create index(
             :identity_support_access_grants,
             [:tenant_id, :support_actor_id, :status, :expires_at],
             name: "identity_support_access_grants_actor_status_index"
           )
  end

  def down do
    drop_if_exists(
      index(
        :identity_support_access_grants,
        [:tenant_id, :support_actor_id, :status, :expires_at],
        name: "identity_support_access_grants_actor_status_index"
      )
    )

    drop_if_exists(
      index(:identity_support_access_grants, [:id, :tenant_id],
        name: "identity_support_access_grants_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :identity_support_access_grants,
        :identity_support_access_grants_activation_consistent
      )
    )

    drop_if_exists(
      constraint(
        :identity_support_access_grants,
        :identity_support_access_grants_independent_approval
      )
    )

    drop_if_exists(
      constraint(
        :identity_support_access_grants,
        :identity_support_access_grants_maximum_lifetime
      )
    )

    drop_if_exists(
      constraint(:identity_support_access_grants, :identity_support_access_grants_scope_nonempty)
    )

    drop_if_exists(
      constraint(
        :identity_support_access_grants,
        :identity_support_access_grants_lock_version_positive
      )
    )

    drop_if_exists(
      constraint(:identity_support_access_grants, :identity_support_access_grants_status_allowed)
    )

    drop(
      constraint(
        :identity_support_access_grants,
        "identity_support_access_grants_session_tenant_fkey"
      )
    )

    drop(table(:identity_support_access_grants))
  end
end
