defmodule Chimwemwe.Repo.Migrations.AddClassroomFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:classroom_teaching_assignments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :participation_id,
        references(:people_participations,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "classroom_teaching_assignments_participation_id_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:class_id, :uuid, null: false)
      add(:effective_from, :date, null: false)
      add(:effective_until, :date, null: false)
      add(:lock_version, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create index(:classroom_teaching_assignments, [:id, :tenant_id],
             name: "classroom_teaching_assignments_id_tenant_idx",
             unique: true
           )

    create index(
             :classroom_teaching_assignments,
             [:tenant_id, :participation_id, :effective_from],
             name: "classroom_teaching_assignments_interval_idx"
           )

    create table(:classroom_enrolments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :participation_id,
        references(:people_participations,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "classroom_enrolments_participation_id_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :academic_year_id,
        references(:academic_years,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "classroom_enrolments_academic_year_id_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:calendar_revision, :text, null: false)
      add(:effective_from, :date, null: false)
      add(:effective_until, :date, null: false)
      add(:lock_version, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:classroom_enrolments, :classroom_enrolments_version,
             check: """
               lock_version IN (1, 2)
             """
           )

    create constraint(:classroom_enrolments, :classroom_enrolments_interval,
             check: """
               effective_until > effective_from
             """
           )

    create constraint(:classroom_enrolments, :classroom_enrolments_revision,
             check: """
               calendar_revision ~ '^[0-9a-f]{64}$'
             """
           )

    create index(:classroom_enrolments, [:id, :tenant_id],
             name: "classroom_enrolments_id_tenant_idx",
             unique: true
           )

    create index(:classroom_enrolments, [:tenant_id, :participation_id, :academic_year_id],
             name: "classroom_enrolments_scope_idx",
             unique: true
           )

    create table(:classroom_classes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    create constraint(:classroom_teaching_assignments, :classroom_teaching_assignments_version,
             check: """
               lock_version IN (1, 2)
             """
           )

    create constraint(:classroom_teaching_assignments, :classroom_teaching_assignments_interval,
             check: """
               effective_until > effective_from
             """
           )

    alter table(:classroom_classes) do
      add(:tenant_id, :uuid, null: false)

      add(
        :institutional_unit_id,
        references(:institutional_units,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "classroom_classes_institutional_unit_id_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :calendar_id,
        references(:academic_calendars,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "classroom_classes_calendar_id_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :academic_year_id,
        references(:academic_years,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "classroom_classes_academic_year_id_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:calendar_revision, :text, null: false)
      add(:code, :text, null: false)
      add(:label, :text, null: false)
      add(:lock_version, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:classroom_classes, :classroom_classes_version,
             check: """
               lock_version = 1
             """
           )

    create constraint(:classroom_classes, :classroom_classes_code,
             check: """
               code ~ '^[a-z][a-z0-9_]{0,79}$'
             """
           )

    create constraint(:classroom_classes, :classroom_classes_label,
             check: """
               char_length(btrim(label)) BETWEEN 1 AND 160
             """
           )

    create constraint(:classroom_classes, :classroom_classes_revision,
             check: """
               calendar_revision ~ '^[0-9a-f]{64}$'
             """
           )

    create index(:classroom_classes, [:id, :tenant_id],
             name: "classroom_classes_id_tenant_idx",
             unique: true
           )

    create index(:classroom_classes, [:tenant_id, :academic_year_id, :code],
             name: "classroom_classes_scope_idx",
             unique: true
           )

    alter table(:classroom_teaching_assignments) do
      modify(
        :class_id,
        references(:classroom_classes,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "classroom_teaching_assignments_class_id_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    drop_if_exists(
      constraint(:platform_outbox_events, :platform_outbox_classification_domain_boundary)
    )

    create constraint(:platform_outbox_events, :platform_outbox_classification_domain_boundary,
             check: """
               (classification = 'internal' AND aggregate_type NOT LIKE 'people.core.%' AND aggregate_type NOT LIKE 'classroom.core.%') OR (classification = 'restricted' AND aggregate_type IN ('people.core.person', 'people.core.participation', 'people.core.account') AND event_type LIKE 'people.core.%') OR (classification = 'restricted' AND aggregate_type IN ('classroom.core.class', 'classroom.core.enrolment', 'classroom.core.assignment', 'classroom.core.placement') AND event_type LIKE 'classroom.core.%')
             """
           )

    create table(:classroom_placements, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :enrolment_id,
        references(:classroom_enrolments,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "classroom_placements_enrolment_id_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :class_id,
        references(:classroom_classes,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "classroom_placements_class_id_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:effective_from, :date, null: false)
      add(:effective_until, :date, null: false)
      add(:lock_version, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:classroom_placements, :classroom_placements_version,
             check: """
               lock_version IN (1, 2)
             """
           )

    create constraint(:classroom_placements, :classroom_placements_interval,
             check: """
               effective_until > effective_from
             """
           )

    create index(:classroom_placements, [:id, :tenant_id],
             name: "classroom_placements_id_tenant_idx",
             unique: true
           )

    create index(:classroom_placements, [:tenant_id, :enrolment_id, :effective_from],
             name: "classroom_placements_interval_idx"
           )

    execute("""
    CREATE FUNCTION classroom_record_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE
      yr academic_years%ROWTYPE;
      cal academic_calendars%ROWTYPE;
      cls classroom_classes%ROWTYPE;
      enr classroom_enrolments%ROWTYPE;
      part people_participations%ROWTYPE;
      local_day date;
    BEGIN
      IF current_setting('transaction_isolation') <> 'read committed' THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'classroom writes require read committed isolation';
      END IF;
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'classroom history is retained';
      END IF;
      IF TG_TABLE_NAME = 'people_participations' THEN
        IF NEW.effective_until IS NOT NULL AND (
          EXISTS (SELECT 1 FROM classroom_enrolments WHERE tenant_id = NEW.tenant_id AND participation_id = NEW.id AND effective_until > NEW.effective_until)
          OR EXISTS (SELECT 1 FROM classroom_teaching_assignments WHERE tenant_id = NEW.tenant_id AND participation_id = NEW.id AND effective_until > NEW.effective_until)) THEN
          RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'end dependent classroom intervals first';
        END IF;
        RETURN NEW;
      END IF;
      IF TG_OP = 'INSERT' AND NEW.lock_version <> 1 THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid initial classroom version';
      END IF;
      IF TG_TABLE_NAME = 'classroom_classes' THEN
        IF TG_OP = 'UPDATE' THEN
          RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'class identity is immutable';
        END IF;
        SELECT * INTO yr FROM academic_years WHERE id = NEW.academic_year_id AND tenant_id = NEW.tenant_id FOR SHARE;
        SELECT * INTO cal FROM academic_calendars WHERE id = yr.calendar_id AND tenant_id = NEW.tenant_id FOR SHARE;
        IF yr.id IS NULL OR cal.id IS NULL OR yr.status <> 'published' OR cal.status <> 'active'
          OR NEW.calendar_revision <> yr.candidate_revision OR NEW.calendar_id <> cal.id
          OR NEW.institutional_unit_id <> cal.institutional_unit_id THEN
          RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'exact published classroom year required';
        END IF;
      ELSE
        IF TG_TABLE_NAME IN ('classroom_enrolments', 'classroom_teaching_assignments') THEN
          SELECT * INTO part FROM people_participations WHERE tenant_id = NEW.tenant_id AND id = NEW.participation_id FOR UPDATE;
          IF part.id IS NULL OR NEW.effective_from < part.effective_from
            OR (part.effective_until IS NOT NULL AND NEW.effective_until > part.effective_until) THEN
            RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'classroom interval requires matching participation';
          END IF;
        END IF;
        IF TG_TABLE_NAME = 'classroom_enrolments' THEN
          SELECT * INTO yr FROM academic_years WHERE id = NEW.academic_year_id AND tenant_id = NEW.tenant_id FOR SHARE;
          SELECT * INTO cal FROM academic_calendars WHERE id = yr.calendar_id AND tenant_id = NEW.tenant_id FOR SHARE;
          IF part.kind <> 'student' OR yr.id IS NULL OR cal.id IS NULL OR yr.status <> 'published' OR cal.status <> 'active'
            OR NEW.calendar_revision <> yr.candidate_revision OR part.institutional_unit_id <> cal.institutional_unit_id THEN
            RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'student and published institution year required';
          END IF;
          IF TG_OP = 'UPDATE' AND EXISTS (SELECT 1 FROM classroom_placements WHERE tenant_id = NEW.tenant_id AND enrolment_id = NEW.id AND effective_until > NEW.effective_until) THEN
            RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'end placements before enrolment';
          END IF;
        ELSE
          IF TG_TABLE_NAME = 'classroom_placements' THEN
            SELECT * INTO enr FROM classroom_enrolments WHERE tenant_id = NEW.tenant_id AND id = NEW.enrolment_id FOR UPDATE;
            IF enr.id IS NULL OR NEW.effective_from < enr.effective_from OR NEW.effective_until > enr.effective_until THEN
              RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'placement requires effective enrolment';
            END IF;
          END IF;
          SELECT * INTO cls FROM classroom_classes WHERE tenant_id = NEW.tenant_id AND id = NEW.class_id FOR SHARE;
          SELECT * INTO yr FROM academic_years WHERE id = cls.academic_year_id AND tenant_id = NEW.tenant_id FOR SHARE;
          SELECT * INTO cal FROM academic_calendars WHERE id = yr.calendar_id AND tenant_id = NEW.tenant_id FOR SHARE;
          IF cls.id IS NULL OR yr.id IS NULL OR cal.id IS NULL OR yr.status <> 'published' OR cal.status <> 'active' OR cls.calendar_revision <> yr.candidate_revision
            OR cls.calendar_id <> cal.id OR cls.institutional_unit_id <> cal.institutional_unit_id THEN
            RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'matching class publication required';
          END IF;
          IF TG_TABLE_NAME = 'classroom_teaching_assignments' THEN
            IF part.kind <> 'staff' OR part.institutional_unit_id <> cls.institutional_unit_id OR EXISTS (
              SELECT 1 FROM classroom_teaching_assignments WHERE tenant_id = NEW.tenant_id AND participation_id = NEW.participation_id AND class_id = NEW.class_id AND id <> NEW.id
                AND effective_from < NEW.effective_until AND NEW.effective_from < effective_until) THEN
              RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid or overlapping teaching assignment';
            END IF;
          ELSIF enr.academic_year_id <> cls.academic_year_id OR enr.calendar_revision <> cls.calendar_revision OR EXISTS (
            SELECT 1 FROM classroom_placements WHERE tenant_id = NEW.tenant_id AND enrolment_id = NEW.enrolment_id AND id <> NEW.id
              AND effective_from < NEW.effective_until AND NEW.effective_from < effective_until) THEN
            RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid or overlapping class placement';
          END IF;
        END IF;
        IF NEW.effective_from < yr.start_on OR NEW.effective_until > yr.end_on + 1 THEN
          RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'classroom interval outside year';
        END IF;
        local_day := (statement_timestamp() AT TIME ZONE yr.time_zone)::date;
        IF TG_OP = 'UPDATE' AND (
          (to_jsonb(NEW) - ARRAY['effective_until','lock_version']) IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['effective_until','lock_version'])
          OR OLD.lock_version <> 1 OR NEW.lock_version <> 2
          OR NEW.effective_until >= OLD.effective_until OR NEW.effective_until < local_day) THEN
          RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid classroom ending';
        END IF;
      END IF;
      PERFORM 1 FROM institutional_units WHERE id = cal.institutional_unit_id AND tenant_id = NEW.tenant_id AND status = 'published' FOR SHARE;
      IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'published institution required';
      END IF;
      RETURN NEW;
    END $$;
    """)

    execute("""
    CREATE TRIGGER classroom_classes_classroom_guard BEFORE INSERT OR UPDATE OR DELETE ON classroom_classes FOR EACH ROW EXECUTE FUNCTION classroom_record_guard();
    """)

    execute("""
    CREATE TRIGGER classroom_enrolments_classroom_guard BEFORE INSERT OR UPDATE OR DELETE ON classroom_enrolments FOR EACH ROW EXECUTE FUNCTION classroom_record_guard();
    """)

    execute("""
    CREATE TRIGGER classroom_teaching_assignments_classroom_guard BEFORE INSERT OR UPDATE OR DELETE ON classroom_teaching_assignments FOR EACH ROW EXECUTE FUNCTION classroom_record_guard();
    """)

    execute("""
    CREATE TRIGGER classroom_placements_classroom_guard BEFORE INSERT OR UPDATE OR DELETE ON classroom_placements FOR EACH ROW EXECUTE FUNCTION classroom_record_guard();
    """)

    execute("""
    CREATE TRIGGER people_participations_classroom_guard BEFORE UPDATE OF effective_until ON people_participations FOR EACH ROW EXECUTE FUNCTION classroom_record_guard();
    """)
  end

  def down do
    execute("""
    DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM classroom_classes) OR EXISTS (SELECT 1 FROM classroom_enrolments)
        OR EXISTS (SELECT 1 FROM classroom_teaching_assignments) OR EXISTS (SELECT 1 FROM classroom_placements)
        OR EXISTS (SELECT 1 FROM platform_authority_audit_events WHERE aggregate_type LIKE 'classroom.core.%')
        OR EXISTS (SELECT 1 FROM platform_outbox_events WHERE aggregate_type LIKE 'classroom.core.%')
        OR EXISTS (SELECT 1 FROM platform_authority_action_idempotency WHERE aggregate_type LIKE 'classroom.core.%') THEN
        RAISE EXCEPTION 'retained classroom foundation cannot be rolled back';
      END IF;
    END $$;
    """)

    execute("""
    DROP TRIGGER people_participations_classroom_guard ON people_participations;
    """)

    execute("""
    DROP TRIGGER classroom_placements_classroom_guard ON classroom_placements;
    """)

    execute("""
    DROP TRIGGER classroom_teaching_assignments_classroom_guard ON classroom_teaching_assignments;
    """)

    execute("""
    DROP TRIGGER classroom_enrolments_classroom_guard ON classroom_enrolments;
    """)

    execute("""
    DROP TRIGGER classroom_classes_classroom_guard ON classroom_classes;
    """)

    execute("""
    DROP FUNCTION classroom_record_guard();
    """)

    drop_if_exists(
      index(:classroom_placements, [:tenant_id, :enrolment_id, :effective_from],
        name: "classroom_placements_interval_idx"
      )
    )

    drop_if_exists(
      index(:classroom_placements, [:id, :tenant_id], name: "classroom_placements_id_tenant_idx")
    )

    drop_if_exists(constraint(:classroom_placements, :classroom_placements_interval))

    drop_if_exists(constraint(:classroom_placements, :classroom_placements_version))

    drop(constraint(:classroom_placements, "classroom_placements_class_id_fk"))

    drop(constraint(:classroom_placements, "classroom_placements_enrolment_id_fk"))

    drop(table(:classroom_placements))

    drop_if_exists(
      constraint(:platform_outbox_events, :platform_outbox_classification_domain_boundary)
    )

    create constraint(:platform_outbox_events, :platform_outbox_classification_domain_boundary,
             check: """
               (classification = 'internal' AND aggregate_type NOT LIKE 'people.core.%') OR (classification = 'restricted' AND aggregate_type IN ('people.core.person', 'people.core.participation', 'people.core.account') AND event_type LIKE 'people.core.%')
             """
           )

    drop(
      constraint(:classroom_teaching_assignments, "classroom_teaching_assignments_class_id_fk")
    )

    drop_if_exists(
      index(:classroom_classes, [:tenant_id, :academic_year_id, :code],
        name: "classroom_classes_scope_idx"
      )
    )

    drop_if_exists(
      index(:classroom_classes, [:id, :tenant_id], name: "classroom_classes_id_tenant_idx")
    )

    drop_if_exists(constraint(:classroom_classes, :classroom_classes_revision))

    drop_if_exists(constraint(:classroom_classes, :classroom_classes_label))

    drop_if_exists(constraint(:classroom_classes, :classroom_classes_code))

    drop_if_exists(constraint(:classroom_classes, :classroom_classes_version))

    drop(constraint(:classroom_classes, "classroom_classes_academic_year_id_fk"))

    drop(constraint(:classroom_classes, "classroom_classes_calendar_id_fk"))

    drop(constraint(:classroom_classes, "classroom_classes_institutional_unit_id_fk"))

    alter table(:classroom_classes) do
      remove(:inserted_at)
      remove(:lock_version)
      remove(:label)
      remove(:code)
      remove(:calendar_revision)
      remove(:academic_year_id)
      remove(:calendar_id)
      remove(:institutional_unit_id)
      remove(:tenant_id)
    end

    drop_if_exists(
      constraint(:classroom_teaching_assignments, :classroom_teaching_assignments_interval)
    )

    drop_if_exists(
      constraint(:classroom_teaching_assignments, :classroom_teaching_assignments_version)
    )

    drop(
      constraint(
        :classroom_teaching_assignments,
        "classroom_teaching_assignments_participation_id_fk"
      )
    )

    alter table(:classroom_teaching_assignments) do
      modify(:class_id, :uuid)
    end

    drop(table(:classroom_classes))

    drop_if_exists(
      index(:classroom_enrolments, [:tenant_id, :participation_id, :academic_year_id],
        name: "classroom_enrolments_scope_idx"
      )
    )

    drop_if_exists(
      index(:classroom_enrolments, [:id, :tenant_id], name: "classroom_enrolments_id_tenant_idx")
    )

    drop_if_exists(constraint(:classroom_enrolments, :classroom_enrolments_revision))

    drop_if_exists(constraint(:classroom_enrolments, :classroom_enrolments_interval))

    drop_if_exists(constraint(:classroom_enrolments, :classroom_enrolments_version))

    drop(constraint(:classroom_enrolments, "classroom_enrolments_academic_year_id_fk"))

    drop(constraint(:classroom_enrolments, "classroom_enrolments_participation_id_fk"))

    drop(table(:classroom_enrolments))

    drop_if_exists(
      index(:classroom_teaching_assignments, [:tenant_id, :participation_id, :effective_from],
        name: "classroom_teaching_assignments_interval_idx"
      )
    )

    drop_if_exists(
      index(:classroom_teaching_assignments, [:id, :tenant_id],
        name: "classroom_teaching_assignments_id_tenant_idx"
      )
    )

    drop(table(:classroom_teaching_assignments))
  end
end
