defmodule Chimwemwe.Repo.Migrations.AddInstitutionalStructureFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and manually reordered so tenant-qualified destination indexes exist before
  their dependent compound foreign keys.
  """

  use Ecto.Migration

  def up do
    create table(:institutional_units, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:display_name, :text, null: false)
      add(:classification, :text, null: false, default: "institution")
      add(:time_zone, :text, null: false)
      add(:status, :text, null: false, default: "draft")
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:institutional_units, :institutional_units_classification,
             check: """
               classification = 'institution'
             """
           )

    create constraint(:institutional_units, :institutional_units_name,
             check: """
               char_length(btrim(display_name)) BETWEEN 1 AND 200
             """
           )

    create constraint(:institutional_units, :institutional_units_zone,
             check: """
               char_length(time_zone) BETWEEN 1 AND 100
             """
           )

    create constraint(:institutional_units, :institutional_units_state,
             check: """
               (status = 'draft' AND lock_version IN (1, 2)) OR
               (status = 'published' AND lock_version = 3)
             """
           )

    create index(:institutional_units, [:id, :tenant_id],
             name: "institutional_units_id_tenant_idx",
             unique: true
           )

    create table(:institution_initial_operator_assignments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :institutional_unit_id,
        references(:institutional_units,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "institution_initial_operator_assignments_institutional_unit_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :legal_entity_id,
        references(:organization_legal_entities,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "institution_initial_operator_assignments_legal_entity_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:legal_entity_version, :bigint, null: false)
      add(:evidence_reference, :uuid, null: false)
      add(:effective_from, :date, null: false)
      add(:verification, :map, null: false)
      add(:recorded_by_actor_id, :uuid, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(
             :institution_initial_operator_assignments,
             :institution_operator_legal_version,
             check: """
               legal_entity_version >= 1
             """
           )

    create index(:institution_initial_operator_assignments, [:id, :tenant_id],
             name: "institution_initial_operator_assignments_id_tenant_idx",
             unique: true
           )

    create index(:institution_initial_operator_assignments, [:institutional_unit_id, :tenant_id],
             name: "institution_initial_operator_assignments_unit_idx",
             unique: true
           )

    create table(:institution_publications, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :institutional_unit_id,
        references(:institutional_units,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "institution_publications_institutional_unit_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :operator_assignment_id,
        references(:institution_initial_operator_assignments,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "institution_publications_operator_assignment_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:verification, :map, null: false)
      add(:recorded_by_actor_id, :uuid, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create index(:institution_publications, [:id, :tenant_id],
             name: "institution_publications_id_tenant_idx",
             unique: true
           )

    create index(:institution_publications, [:institutional_unit_id, :tenant_id],
             name: "institution_publications_unit_idx",
             unique: true
           )
  end

  def down do
    execute("""
    DO $$
    BEGIN
      IF EXISTS (SELECT 1 FROM institution_publications)
         OR EXISTS (SELECT 1 FROM institution_initial_operator_assignments)
         OR EXISTS (SELECT 1 FROM institutional_units)
         OR EXISTS (
           SELECT 1
           FROM platform_authority_audit_events
           WHERE action_name IN (
             'institution.structure.institution.register',
             'institution.structure.operator.assign_initial',
             'institution.structure.institution.publish'
           )
         )
         OR EXISTS (
           SELECT 1
           FROM platform_outbox_events
           WHERE aggregate_type = 'institution.structure.unit'
         )
         OR EXISTS (
           SELECT 1
           FROM platform_authority_action_idempotency
           WHERE action_name IN (
             'institution.structure.institution.register',
             'institution.structure.operator.assign_initial',
             'institution.structure.institution.publish'
           )
         )
      THEN
        RAISE EXCEPTION
          'institution structure rollback requires empty state and durable evidence';
      END IF;
    END
    $$;
    """)

    drop(table(:institution_publications))
    drop(table(:institution_initial_operator_assignments))
    drop(table(:institutional_units))
  end
end
