defmodule Chimwemwe.Repo.Migrations.AddPeopleFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:people_persons, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:display_name, :text, null: false)
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:people_persons, :people_persons_name,
             check: """
               char_length(btrim(display_name)) BETWEEN 1 AND 200
             """
           )

    create constraint(:people_persons, :people_persons_version,
             check: """
               lock_version >= 1
             """
           )

    create index(:people_persons, [:id, :tenant_id],
             name: "people_persons_id_tenant_idx",
             unique: true
           )

    create table(:people_participations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :person_id,
        references(:people_persons,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "people_participations_person_id_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :institutional_unit_id,
        references(:institutional_units,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "people_participations_institutional_unit_id_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:kind, :text, null: false)
      add(:effective_from, :date, null: false)
      add(:effective_until, :date)
      add(:source_reference, :uuid, null: false)
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:people_participations, :people_participations_kind,
             check: """
               kind IN ('student', 'staff')
             """
           )

    create constraint(:people_participations, :people_participations_interval,
             check: """
               effective_until IS NULL OR effective_until > effective_from
             """
           )

    create constraint(:people_participations, :people_participations_version,
             check: """
               lock_version IN (1, 2)
             """
           )

    create index(:people_participations, [:id, :tenant_id],
             name: "people_participations_id_tenant_idx",
             unique: true
           )

    create index(:people_participations, [:person_id, :institutional_unit_id, :kind, :tenant_id],
             name: "people_participations_subject_idx",
             unique: true
           )

    create table(:people_staff_account_associations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :person_id,
        references(:people_persons,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "people_staff_account_associations_person_id_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :participation_id,
        references(:people_participations,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "people_staff_account_associations_participation_id_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :membership_id,
        references(:platform_tenant_memberships,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "people_staff_account_associations_membership_id_fk",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:evidence_reference, :uuid, null: false)
      add(:verification, :map, null: false)
      add(:revoked_at, :utc_datetime_usec)
      add(:revoked_by_actor_id, :uuid)
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(
             :people_staff_account_associations,
             :people_staff_account_associations_state,
             check: """
               (lock_version = 1 AND revoked_at IS NULL AND revoked_by_actor_id IS NULL) OR (lock_version = 2 AND revoked_at IS NOT NULL AND revoked_by_actor_id IS NOT NULL)
             """
           )

    create index(:people_staff_account_associations, [:id, :tenant_id],
             name: "people_staff_account_associations_id_tenant_idx",
             unique: true
           )

    create index(:people_staff_account_associations, [:person_id, :tenant_id],
             name: "people_staff_account_person_idx",
             unique: true,
             where: "revoked_at IS NULL"
           )

    create index(:people_staff_account_associations, [:membership_id, :tenant_id],
             name: "people_staff_account_membership_idx",
             unique: true,
             where: "revoked_at IS NULL"
           )

    execute("""
    CREATE FUNCTION people_record_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE
    part people_participations%ROWTYPE;
    person_version bigint;
    member_actor uuid;
    local_day date;
    proof jsonb;
    BEGIN
    IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'people records require retained history';
    END IF;
    IF TG_OP = 'INSERT' AND NEW.lock_version <> 1 THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid initial people version';
    END IF;
    IF TG_TABLE_NAME = 'people_persons' THEN
    IF TG_OP = 'UPDATE' AND (
    (to_jsonb(NEW) - ARRAY['display_name','lock_version']) IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['display_name','lock_version'])
    OR NEW.lock_version <> OLD.lock_version + 1) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'immutable person identity';
    END IF;
    ELSIF TG_TABLE_NAME = 'people_participations' THEN
    SELECT (statement_timestamp() AT TIME ZONE time_zone)::date INTO local_day
    FROM institutional_units WHERE id = NEW.institutional_unit_id AND tenant_id = NEW.tenant_id AND status = 'published' FOR SHARE;
    IF local_day IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'published exact institution required';
    END IF;
    IF TG_OP = 'UPDATE' AND (
    (to_jsonb(NEW) - ARRAY['effective_until','lock_version']) IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['effective_until','lock_version'])
    OR OLD.effective_until IS NOT NULL OR NEW.effective_until IS NULL
    OR NEW.effective_until < local_day OR NEW.lock_version <> 2 OR OLD.lock_version <> 1) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid participation ending';
    END IF;
    ELSIF TG_TABLE_NAME = 'people_staff_account_associations' THEN
    IF TG_OP = 'UPDATE' THEN
    IF (to_jsonb(NEW) - ARRAY['revoked_at','revoked_by_actor_id','lock_version']) IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['revoked_at','revoked_by_actor_id','lock_version'])
    OR OLD.revoked_at IS NOT NULL OR NEW.revoked_at IS NULL OR NEW.revoked_by_actor_id IS NULL
    OR NEW.lock_version <> 2 OR OLD.lock_version <> 1
    OR NEW.revoked_at < (transaction_timestamp() AT TIME ZONE 'UTC')
    OR NEW.revoked_at > (clock_timestamp() AT TIME ZONE 'UTC') THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid account revocation';
    END IF;
    ELSE
    SELECT * INTO STRICT part FROM people_participations WHERE id = NEW.participation_id AND tenant_id = NEW.tenant_id FOR SHARE;
    SELECT lock_version INTO STRICT person_version FROM people_persons WHERE id = NEW.person_id AND tenant_id = NEW.tenant_id FOR SHARE;
    SELECT actor_id INTO STRICT member_actor FROM platform_tenant_memberships WHERE id = NEW.membership_id AND tenant_id = NEW.tenant_id FOR SHARE;
    SELECT (statement_timestamp() AT TIME ZONE time_zone)::date INTO local_day FROM institutional_units WHERE id = part.institutional_unit_id AND tenant_id = part.tenant_id AND status = 'published' FOR SHARE;
    IF part.person_id <> NEW.person_id OR part.kind <> 'staff' OR local_day IS NULL
    OR part.effective_from > local_day OR (part.effective_until IS NOT NULL AND part.effective_until <= local_day) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'current matching staff participation required';
    END IF;
    proof := NEW.verification;
    IF (jsonb_typeof(proof) = 'object'
    AND proof->>'policy' = 'synthetic.people.staff_account.v1'
    AND proof->>'tenant_id' = NEW.tenant_id::text
    AND proof->>'person_id' = NEW.person_id::text
    AND (proof->>'person_version')::bigint = person_version
    AND proof->>'participation_id' = part.id::text
    AND (proof->>'participation_version')::bigint = part.lock_version
    AND proof->>'membership_id' = NEW.membership_id::text
    AND proof->>'actor_id' = member_actor::text
    AND proof->>'evidence_reference' = NEW.evidence_reference::text
    AND proof->'matched' = 'true'::jsonb AND proof->'human_account' = 'true'::jsonb
    AND (proof->>'checked_at')::timestamptz >= transaction_timestamp()
    AND (proof->>'checked_at')::timestamptz <= clock_timestamp()
    AND proof - ARRAY['policy','tenant_id','person_id','person_version','participation_id','participation_version','membership_id','actor_id','evidence_reference','matched','human_account','checked_at'] = '{}'::jsonb) IS DISTINCT FROM TRUE THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid staff account proof';
    END IF;
    END IF;
    END IF;
    RETURN NEW;
    END $$;
    """)

    execute("""
    CREATE TRIGGER people_persons_guard BEFORE INSERT OR UPDATE OR DELETE ON people_persons FOR EACH ROW EXECUTE FUNCTION people_record_guard();
    """)

    execute("""
    CREATE TRIGGER people_participations_guard BEFORE INSERT OR UPDATE OR DELETE ON people_participations FOR EACH ROW EXECUTE FUNCTION people_record_guard();
    """)

    execute("""
    CREATE TRIGGER people_staff_account_associations_guard BEFORE INSERT OR UPDATE OR DELETE ON people_staff_account_associations FOR EACH ROW EXECUTE FUNCTION people_record_guard();
    """)
  end

  def down do
    execute("""
    DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM people_persons)
         OR EXISTS (SELECT 1 FROM platform_authority_audit_events WHERE action_name LIKE 'people.core.%')
         OR EXISTS (SELECT 1 FROM platform_outbox_events WHERE aggregate_type LIKE 'people.core.%')
         OR EXISTS (SELECT 1 FROM platform_authority_action_idempotency WHERE action_name LIKE 'people.core.%') THEN
        RAISE EXCEPTION 'retained people foundation cannot be rolled back';
      END IF;
    END $$;
    """)

    execute("""
    DROP TRIGGER people_staff_account_associations_guard ON people_staff_account_associations;
    """)

    execute("""
    DROP TRIGGER people_participations_guard ON people_participations;
    """)

    execute("""
    DROP TRIGGER people_persons_guard ON people_persons;
    """)

    execute("""
    DROP FUNCTION people_record_guard();
    """)

    drop_if_exists(
      index(:people_staff_account_associations, [:membership_id, :tenant_id],
        name: "people_staff_account_membership_idx"
      )
    )

    drop_if_exists(
      index(:people_staff_account_associations, [:person_id, :tenant_id],
        name: "people_staff_account_person_idx"
      )
    )

    drop_if_exists(
      index(:people_staff_account_associations, [:id, :tenant_id],
        name: "people_staff_account_associations_id_tenant_idx"
      )
    )

    drop_if_exists(
      constraint(:people_staff_account_associations, :people_staff_account_associations_state)
    )

    drop(
      constraint(
        :people_staff_account_associations,
        "people_staff_account_associations_membership_id_fk"
      )
    )

    drop(
      constraint(
        :people_staff_account_associations,
        "people_staff_account_associations_participation_id_fk"
      )
    )

    drop(
      constraint(
        :people_staff_account_associations,
        "people_staff_account_associations_person_id_fk"
      )
    )

    drop(table(:people_staff_account_associations))

    drop_if_exists(
      index(:people_participations, [:person_id, :institutional_unit_id, :kind, :tenant_id],
        name: "people_participations_subject_idx"
      )
    )

    drop_if_exists(
      index(:people_participations, [:id, :tenant_id],
        name: "people_participations_id_tenant_idx"
      )
    )

    drop_if_exists(constraint(:people_participations, :people_participations_version))

    drop_if_exists(constraint(:people_participations, :people_participations_interval))

    drop_if_exists(constraint(:people_participations, :people_participations_kind))

    drop(constraint(:people_participations, "people_participations_institutional_unit_id_fk"))

    drop(constraint(:people_participations, "people_participations_person_id_fk"))

    drop(table(:people_participations))

    drop_if_exists(
      index(:people_persons, [:id, :tenant_id], name: "people_persons_id_tenant_idx")
    )

    drop_if_exists(constraint(:people_persons, :people_persons_version))

    drop_if_exists(constraint(:people_persons, :people_persons_name))

    drop(table(:people_persons))
  end
end
