defmodule Chimwemwe.Repo.Migrations.Phase2IdentityLinkFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:identity_connections, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:name, :text, null: false)
      add(:protocol, :text, null: false)
      add(:issuer, :text, null: false)
      add(:application_identifier, :text, null: false)
      add(:secret_reference, :text, null: false)
      add(:assurance_mapping, :map, null: false, default: %{})
      add(:configuration_version, :bigint, null: false, default: 1)
      add(:status, :text, null: false, default: "draft")
      add(:lock_version, :bigint, null: false, default: 1)
      add(:qualified_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:identity_connections, :identity_connections_protocol_allowed,
             check: """
               protocol IN ('oidc', 'saml')
             """
           )

    create constraint(:identity_connections, :identity_connections_status_allowed,
             check: """
               status IN ('draft', 'qualified', 'active', 'suspended', 'retired')
             """
           )

    create constraint(:identity_connections, :identity_connections_configuration_version_positive,
             check: """
               configuration_version >= 1
             """
           )

    create constraint(:identity_connections, :identity_connections_lock_version_positive,
             check: """
               lock_version >= 1
             """
           )

    create constraint(:identity_connections, :identity_connections_assurance_mapping_object,
             check: """
               jsonb_typeof(assurance_mapping) = 'object'
             """
           )

    create index(:identity_connections, [:id, :tenant_id],
             name: "identity_connections_id_tenant_index",
             unique: true
           )

    create index(:identity_connections, [:tenant_id, :name],
             name: "identity_connections_tenant_name_index",
             unique: true
           )

    create table(:identity_external_identity_links, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:actor_id, :uuid, null: false)
      add(:origin_tenant_id, :uuid, null: false)
      add(:connection_id, :uuid, null: false)
      add(:protocol, :text, null: false)
      add(:issuer, :text, null: false)
      add(:subject, :text, null: false)
      add(:connection_configuration_version, :bigint, null: false)
      add(:status, :text, null: false, default: "active")
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(
             :identity_external_identity_links,
             :identity_external_identity_links_protocol_allowed,
             check: """
               protocol IN ('oidc', 'saml')
             """
           )

    create constraint(
             :identity_external_identity_links,
             :identity_external_identity_links_status_allowed,
             check: """
               status IN ('active', 'revoked')
             """
           )

    create constraint(
             :identity_external_identity_links,
             :identity_external_identity_links_lock_version_positive,
             check: """
               lock_version >= 1
             """
           )

    create index(:identity_external_identity_links, [:protocol, :issuer, :subject],
             name: "identity_external_identity_links_external_key_index",
             unique: true
           )

    create index(:identity_external_identity_links, [:actor_id],
             name: "identity_external_identity_links_actor_index"
           )

    create table(:identity_invitations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:actor_id, :uuid, null: false)
      add(:membership_id, :uuid, null: false)
      add(:role_id, :uuid, null: false)
      add(:connection_id, :uuid, null: false)
      add(:token_digest, :binary, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:expires_at, :utc_datetime_usec, null: false)
      add(:accepted_at, :utc_datetime_usec)
      add(:external_identity_link_id, :uuid)
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:identity_invitations, :identity_invitations_token_digest_sha256,
             check: """
               octet_length(token_digest) = 32
             """
           )

    create constraint(:identity_invitations, :identity_invitations_status_allowed,
             check: """
               status IN ('pending', 'accepted', 'revoked')
             """
           )

    create constraint(:identity_invitations, :identity_invitations_lock_version_positive,
             check: """
               lock_version >= 1
             """
           )

    create constraint(:identity_invitations, :identity_invitations_acceptance_consistent,
             check: """
               (status = 'accepted' AND accepted_at IS NOT NULL AND external_identity_link_id IS NOT NULL) OR
             (status IN ('pending', 'revoked') AND accepted_at IS NULL AND external_identity_link_id IS NULL)

             """
           )

    create constraint(:identity_invitations, :identity_invitations_maximum_lifetime,
             check: """
               expires_at > inserted_at AND expires_at <= inserted_at + INTERVAL '30 minutes'
             """
           )

    create index(:identity_invitations, [:id, :tenant_id],
             name: "identity_invitations_id_tenant_index",
             unique: true
           )

    create index(:identity_invitations, [:tenant_id, :token_digest],
             name: "identity_invitations_token_digest_index",
             unique: true
           )

    create index(:identity_invitations, [:tenant_id, :membership_id, :status, :expires_at],
             name: "identity_invitations_membership_status_index"
           )
  end

  def down do
    drop_if_exists(
      index(:identity_invitations, [:tenant_id, :membership_id, :status, :expires_at],
        name: "identity_invitations_membership_status_index"
      )
    )

    drop_if_exists(
      index(:identity_invitations, [:tenant_id, :token_digest],
        name: "identity_invitations_token_digest_index"
      )
    )

    drop_if_exists(
      index(:identity_invitations, [:id, :tenant_id],
        name: "identity_invitations_id_tenant_index"
      )
    )

    drop_if_exists(constraint(:identity_invitations, :identity_invitations_maximum_lifetime))

    drop_if_exists(constraint(:identity_invitations, :identity_invitations_acceptance_consistent))

    drop_if_exists(constraint(:identity_invitations, :identity_invitations_lock_version_positive))

    drop_if_exists(constraint(:identity_invitations, :identity_invitations_status_allowed))

    drop_if_exists(constraint(:identity_invitations, :identity_invitations_token_digest_sha256))

    drop(table(:identity_invitations))

    drop_if_exists(
      index(:identity_external_identity_links, [:actor_id],
        name: "identity_external_identity_links_actor_index"
      )
    )

    drop_if_exists(
      index(:identity_external_identity_links, [:protocol, :issuer, :subject],
        name: "identity_external_identity_links_external_key_index"
      )
    )

    drop_if_exists(
      constraint(
        :identity_external_identity_links,
        :identity_external_identity_links_lock_version_positive
      )
    )

    drop_if_exists(
      constraint(
        :identity_external_identity_links,
        :identity_external_identity_links_status_allowed
      )
    )

    drop_if_exists(
      constraint(
        :identity_external_identity_links,
        :identity_external_identity_links_protocol_allowed
      )
    )

    drop(table(:identity_external_identity_links))

    drop_if_exists(
      index(:identity_connections, [:tenant_id, :name],
        name: "identity_connections_tenant_name_index"
      )
    )

    drop_if_exists(
      index(:identity_connections, [:id, :tenant_id],
        name: "identity_connections_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(:identity_connections, :identity_connections_assurance_mapping_object)
    )

    drop_if_exists(constraint(:identity_connections, :identity_connections_lock_version_positive))

    drop_if_exists(
      constraint(:identity_connections, :identity_connections_configuration_version_positive)
    )

    drop_if_exists(constraint(:identity_connections, :identity_connections_status_allowed))

    drop_if_exists(constraint(:identity_connections, :identity_connections_protocol_allowed))

    drop(table(:identity_connections))
  end
end
