defmodule Chimwemwe.Repo.Migrations.TemporalFactAndConsumerReconciliation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:platform_temporal_qualification_consumer_bases, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:consumer_id, :uuid, null: false)
      add(:aggregate_id, :uuid, null: false)

      add(
        :revision_id,
        references(:platform_temporal_qualification_revisions,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "platform_temporal_consumer_basis_revision_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:operation_id, :uuid, null: false)
      add(:basis_version, :bigint, null: false)

      add(:predecessor_basis_id, :uuid)

      add(:reason_code, :text, null: false)
      add(:recorded_at, :utc_datetime_usec, null: false)
    end

    create constraint(
             :platform_temporal_qualification_consumer_bases,
             :platform_temporal_consumer_basis_chain_shape,
             check: """
               (basis_version = 1 AND predecessor_basis_id IS NULL) OR
             (basis_version > 1 AND predecessor_basis_id IS NOT NULL)

             """
           )

    create constraint(
             :platform_temporal_qualification_consumer_bases,
             :platform_temporal_consumer_basis_reason_shape,
             check: """
               char_length(reason_code) BETWEEN 1 AND 80 AND
             reason_code ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*$'

             """
           )

    create index(:platform_temporal_qualification_consumer_bases, [:id, :tenant_id],
             name: "platform_temporal_consumer_bases_id_tenant_index",
             unique: true
           )

    create index(
             :platform_temporal_qualification_consumer_bases,
             [:id, :tenant_id, :consumer_id, :aggregate_id],
             name: "platform_temporal_consumer_bases_chain_index",
             unique: true
           )

    create index(
             :platform_temporal_qualification_consumer_bases,
             [:tenant_id, :consumer_id, :basis_version],
             name: "platform_temporal_consumer_bases_version_index",
             unique: true
           )

    create index(
             :platform_temporal_qualification_consumer_bases,
             [:tenant_id, :consumer_id, :recorded_at, :id],
             name: "platform_temporal_consumer_bases_history_index"
           )

    create index(
             :platform_temporal_qualification_consumer_bases,
             [:tenant_id, :predecessor_basis_id],
             name: "platform_temporal_consumer_bases_successor_index",
             unique: true,
             where: "predecessor_basis_id IS NOT NULL"
           )

    execute("""
    ALTER TABLE platform_temporal_qualification_consumer_bases
    ADD CONSTRAINT platform_temporal_consumer_basis_predecessor_tenant_fkey
    FOREIGN KEY (predecessor_basis_id, tenant_id)
    REFERENCES platform_temporal_qualification_consumer_bases (id, tenant_id)
    MATCH SIMPLE
    ON DELETE RESTRICT;
    """)

    execute("""
    CREATE FUNCTION guard_platform_temporal_consumer_basis()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      prior_version bigint;
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_consumer_basis_delete_forbidden',
          MESSAGE = 'temporal qualification consumer basis deletion is forbidden';
      END IF;

      IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_consumer_basis_immutable',
          MESSAGE = 'temporal qualification consumer bases are immutable';
      END IF;

      NEW.recorded_at := transaction_timestamp() AT TIME ZONE 'UTC';

      IF NOT EXISTS (
        SELECT 1
        FROM platform_temporal_qualification_aggregates AS aggregate
        JOIN platform_temporal_qualification_revisions AS revision
          ON revision.tenant_id = aggregate.tenant_id
         AND revision.aggregate_id = aggregate.id
         AND revision.id = aggregate.current_revision_id
        WHERE aggregate.tenant_id = NEW.tenant_id
          AND aggregate.id = NEW.aggregate_id
          AND revision.id = NEW.revision_id
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_consumer_basis_current_revision',
          MESSAGE = 'consumer basis must reference the exact current source revision';
      END IF;

      IF NEW.basis_version > 1 THEN
        SELECT basis_version
        INTO prior_version
        FROM platform_temporal_qualification_consumer_bases
        WHERE id = NEW.predecessor_basis_id
          AND tenant_id = NEW.tenant_id
          AND consumer_id = NEW.consumer_id
          AND aggregate_id = NEW.aggregate_id;

        IF prior_version IS NULL OR NEW.basis_version <> prior_version + 1 THEN
          RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'platform_temporal_consumer_basis_predecessor',
            MESSAGE = 'consumer basis predecessor must be consecutive';
        END IF;
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER platform_temporal_consumer_basis_guard
    BEFORE INSERT OR UPDATE OR DELETE
    ON platform_temporal_qualification_consumer_bases
    FOR EACH ROW
    EXECUTE FUNCTION guard_platform_temporal_consumer_basis();
    """)

    create table(:platform_temporal_qualification_fact_operations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:scope_id, :uuid, null: false)
      add(:kind, :text, null: false)
      add(:target_fact_id, :uuid)
      add(:reason_code, :text, null: false)
      add(:recorded_at, :utc_datetime_usec, null: false)
    end

    create constraint(
             :platform_temporal_qualification_fact_operations,
             :platform_temporal_fact_operation_kind_shape,
             check: """
               (kind = 'record' AND target_fact_id IS NULL) OR
             (kind = 'reverse_and_replace' AND target_fact_id IS NOT NULL)

             """
           )

    create constraint(
             :platform_temporal_qualification_fact_operations,
             :platform_temporal_fact_operation_reason_shape,
             check: """
               char_length(reason_code) BETWEEN 1 AND 80 AND
             reason_code ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*$'

             """
           )

    create index(:platform_temporal_qualification_fact_operations, [:id, :tenant_id],
             name: "platform_temporal_fact_operations_id_tenant_index",
             unique: true
           )

    create index(:platform_temporal_qualification_fact_operations, [:id, :tenant_id, :scope_id],
             name: "platform_temporal_fact_operations_scope_index",
             unique: true
           )

    create index(
             :platform_temporal_qualification_fact_operations,
             [:tenant_id, :scope_id, :recorded_at, :id],
             name: "platform_temporal_fact_operations_history_index"
           )

    create index(:platform_temporal_qualification_fact_operations, [:tenant_id, :target_fact_id],
             name: "platform_temporal_fact_operations_target_index",
             unique: true,
             where: "kind = 'reverse_and_replace'"
           )

    execute("""
    CREATE FUNCTION guard_platform_temporal_fact_operation()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_fact_operation_delete_forbidden',
          MESSAGE = 'temporal qualification fact operation deletion is forbidden';
      END IF;

      IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_fact_operation_immutable',
          MESSAGE = 'temporal qualification fact operations are immutable';
      END IF;

      NEW.recorded_at := transaction_timestamp() AT TIME ZONE 'UTC';

      IF NEW.kind = 'reverse_and_replace' AND NOT EXISTS (
        SELECT 1
        FROM platform_temporal_qualification_facts
        WHERE id = NEW.target_fact_id
          AND tenant_id = NEW.tenant_id
          AND scope_id = NEW.scope_id
          AND kind = 'entry'
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_fact_operation_target',
          MESSAGE = 'temporal qualification correction target is invalid';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER platform_temporal_fact_operation_guard
    BEFORE INSERT OR UPDATE OR DELETE
    ON platform_temporal_qualification_fact_operations
    FOR EACH ROW
    EXECUTE FUNCTION guard_platform_temporal_fact_operation();
    """)

    execute("""
    CREATE OR REPLACE FUNCTION guard_platform_temporal_qualification_fact()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      operation_kind text;
      operation_target uuid;
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_fact_delete_forbidden',
          MESSAGE = 'temporal qualification fact deletion is forbidden';
      END IF;

      IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_fact_immutable',
          MESSAGE = 'temporal qualification facts are immutable';
      END IF;

      NEW.recorded_at := transaction_timestamp() AT TIME ZONE 'UTC';

      SELECT kind, target_fact_id
      INTO operation_kind, operation_target
      FROM platform_temporal_qualification_fact_operations
      WHERE id = NEW.operation_id
        AND tenant_id = NEW.tenant_id
        AND scope_id = NEW.scope_id;

      IF operation_kind IS NULL THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_fact_operation_missing',
          MESSAGE = 'temporal qualification fact operation is missing';
      END IF;

      IF operation_kind = 'record' AND (
        NEW.kind <> 'entry'
        OR EXISTS (
          SELECT 1
          FROM platform_temporal_qualification_facts
          WHERE tenant_id = NEW.tenant_id
            AND operation_id = NEW.operation_id
        )
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_fact_record_shape',
          MESSAGE = 'record operation must create exactly one entry';
      END IF;

      IF operation_kind = 'reverse_and_replace' AND (
        (NEW.kind = 'reversal' AND (
          NEW.reverses_fact_id IS DISTINCT FROM operation_target
          OR EXISTS (
            SELECT 1
            FROM platform_temporal_qualification_facts
            WHERE tenant_id = NEW.tenant_id
              AND operation_id = NEW.operation_id
              AND kind = 'reversal'
          )
        ))
        OR
        (NEW.kind = 'entry' AND EXISTS (
          SELECT 1
          FROM platform_temporal_qualification_facts
          WHERE tenant_id = NEW.tenant_id
            AND operation_id = NEW.operation_id
            AND kind = 'entry'
        ))
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_fact_correction_shape',
          MESSAGE = 'correction operation fact shape is invalid';
      END IF;

      IF NEW.kind = 'reversal' AND NOT EXISTS (
        SELECT 1
        FROM platform_temporal_qualification_facts
        WHERE id = NEW.reverses_fact_id
          AND tenant_id = NEW.tenant_id
          AND scope_id = NEW.scope_id
          AND kind = 'entry'
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_fact_reversal_target',
          MESSAGE = 'temporal qualification reversal target is invalid';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)
  end

  def down do
    execute("""
    DO $$
    BEGIN
      IF EXISTS (SELECT 1 FROM platform_temporal_qualification_consumer_bases)
         OR EXISTS (SELECT 1 FROM platform_temporal_qualification_fact_operations)
      THEN
        RAISE EXCEPTION
          'temporal fact and reconciliation rollback requires empty T1-C retained state';
      END IF;
    END
    $$;
    """)

    execute("""
    DROP TRIGGER platform_temporal_fact_operation_guard
      ON platform_temporal_qualification_fact_operations;
    """)

    execute("""
    DROP FUNCTION guard_platform_temporal_fact_operation();
    """)

    drop_if_exists(
      index(:platform_temporal_qualification_fact_operations, [:tenant_id, :target_fact_id],
        name: "platform_temporal_fact_operations_target_index"
      )
    )

    drop_if_exists(
      index(
        :platform_temporal_qualification_fact_operations,
        [:tenant_id, :scope_id, :recorded_at, :id],
        name: "platform_temporal_fact_operations_history_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_fact_operations, [:id, :tenant_id, :scope_id],
        name: "platform_temporal_fact_operations_scope_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_fact_operations, [:id, :tenant_id],
        name: "platform_temporal_fact_operations_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_fact_operations,
        :platform_temporal_fact_operation_reason_shape
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_fact_operations,
        :platform_temporal_fact_operation_kind_shape
      )
    )

    drop(table(:platform_temporal_qualification_fact_operations))

    execute("""
    DROP TRIGGER platform_temporal_consumer_basis_guard
      ON platform_temporal_qualification_consumer_bases;
    """)

    execute("""
    DROP FUNCTION guard_platform_temporal_consumer_basis();
    """)

    drop(
      constraint(
        :platform_temporal_qualification_consumer_bases,
        "platform_temporal_consumer_basis_predecessor_tenant_fkey"
      )
    )

    drop(
      constraint(
        :platform_temporal_qualification_consumer_bases,
        "platform_temporal_consumer_basis_revision_tenant_fkey"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_consumer_bases, [:tenant_id, :predecessor_basis_id],
        name: "platform_temporal_consumer_bases_successor_index"
      )
    )

    drop_if_exists(
      index(
        :platform_temporal_qualification_consumer_bases,
        [:tenant_id, :consumer_id, :recorded_at, :id],
        name: "platform_temporal_consumer_bases_history_index"
      )
    )

    drop_if_exists(
      index(
        :platform_temporal_qualification_consumer_bases,
        [:tenant_id, :consumer_id, :basis_version],
        name: "platform_temporal_consumer_bases_version_index"
      )
    )

    drop_if_exists(
      index(
        :platform_temporal_qualification_consumer_bases,
        [:id, :tenant_id, :consumer_id, :aggregate_id],
        name: "platform_temporal_consumer_bases_chain_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_consumer_bases, [:id, :tenant_id],
        name: "platform_temporal_consumer_bases_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_consumer_bases,
        :platform_temporal_consumer_basis_reason_shape
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_consumer_bases,
        :platform_temporal_consumer_basis_chain_shape
      )
    )

    drop(table(:platform_temporal_qualification_consumer_bases))

    execute("""
    CREATE OR REPLACE FUNCTION guard_platform_temporal_qualification_fact()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_fact_delete_forbidden',
          MESSAGE = 'temporal qualification fact deletion is forbidden';
      END IF;

      IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_fact_immutable',
          MESSAGE = 'temporal qualification facts are immutable';
      END IF;

      NEW.recorded_at := transaction_timestamp() AT TIME ZONE 'UTC';

      IF NEW.kind = 'reversal' AND NOT EXISTS (
        SELECT 1
        FROM platform_temporal_qualification_facts
        WHERE id = NEW.reverses_fact_id
          AND tenant_id = NEW.tenant_id
          AND scope_id = NEW.scope_id
          AND kind = 'entry'
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_fact_reversal_target',
          MESSAGE = 'temporal qualification reversal target is invalid';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)
  end
end
