defmodule Chimwemwe.Repo.Migrations.AddClassroomAttendance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:classroom_attendance_exposures, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:actor_id, :uuid, null: false)
      add(:day, :date, null: false)
      add(:class_ids, {:array, :uuid}, null: false)
      add(:person_ids, {:array, :uuid}, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:classroom_attendance_exposures, :classroom_attendance_class_budget,
             check: """
               cardinality(class_ids) <= 12
             """
           )

    create constraint(:classroom_attendance_exposures, :classroom_attendance_person_budget,
             check: """
               cardinality(person_ids) <= 720
             """
           )

    create index(:classroom_attendance_exposures, [:tenant_id, :actor_id, :day],
             name: "classroom_attendance_exposure_day_idx",
             unique: true
           )

    drop_if_exists(
      constraint(:platform_outbox_events, :platform_outbox_classification_domain_boundary)
    )

    create constraint(:platform_outbox_events, :platform_outbox_classification_domain_boundary,
             check: """
               (classification = 'internal' AND aggregate_type NOT LIKE 'people.core.%' AND aggregate_type NOT LIKE 'classroom.core.%' AND aggregate_type NOT LIKE 'classroom.attendance.%') OR (classification = 'restricted' AND aggregate_type IN ('people.core.person', 'people.core.participation', 'people.core.account') AND event_type LIKE 'people.core.%') OR (classification = 'restricted' AND aggregate_type IN ('classroom.core.class', 'classroom.core.enrolment', 'classroom.core.assignment', 'classroom.core.placement') AND event_type LIKE 'classroom.core.%') OR (classification = 'restricted' AND aggregate_type = 'classroom.attendance.submission' AND event_type = 'classroom.attendance.submit.completed')
             """
           )

    create table(:classroom_attendance_submissions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :class_id,
        references(:classroom_classes,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "classroom_attendance_submissions_class_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ), null: false)

      add(:local_date, :date, null: false)
      add(:calendar_revision, :text, null: false)
      add(:roster_basis, :text, null: false)
      add(:roster, :map, null: false)
      add(:marks, :map, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:classroom_attendance_submissions, :classroom_attendance_basis,
             check: """
               roster_basis ~ '^[0-9a-f]{64}$'
             """
           )

    create constraint(:classroom_attendance_submissions, :classroom_attendance_revision,
             check: """
               calendar_revision ~ '^[0-9a-f]{64}$'
             """
           )

    create constraint(:classroom_attendance_submissions, :classroom_attendance_roster,
             check: """
               jsonb_typeof(roster->'students') = 'array' AND jsonb_array_length(roster->'students') BETWEEN 1 AND 60
             """
           )

    create constraint(:classroom_attendance_submissions, :classroom_attendance_marks,
             check: """
               jsonb_typeof(marks) = 'object'
             """
           )

    create index(:classroom_attendance_submissions, [:tenant_id, :class_id, :local_date],
             name: "classroom_attendance_day_idx",
             unique: true
           )

    execute("""
    DO $migration$ BEGIN
        CREATE FUNCTION classroom_attendance_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'attendance is retained and immutable';
    END $$;
    CREATE TRIGGER classroom_attendance_immutable BEFORE UPDATE OR DELETE ON classroom_attendance_submissions
      FOR EACH ROW EXECUTE FUNCTION classroom_attendance_immutable();
        END $migration$;
    """)
  end

  def down do
    execute("""
    DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM classroom_attendance_submissions) OR EXISTS (SELECT 1 FROM classroom_attendance_exposures)
        OR EXISTS (SELECT 1 FROM platform_outbox_events WHERE aggregate_type LIKE 'classroom.attendance.%')
        OR EXISTS (SELECT 1 FROM platform_authority_audit_events WHERE aggregate_type LIKE 'classroom.attendance.%') THEN
        RAISE EXCEPTION 'retained attendance evidence requires forward repair';
      END IF;
    END $$;
    """)
    execute("""
    DO $migration$ BEGIN DROP TRIGGER classroom_attendance_immutable ON classroom_attendance_submissions; DROP FUNCTION classroom_attendance_immutable(); END $migration$;
    """)

    drop_if_exists(
      index(:classroom_attendance_submissions, [:tenant_id, :class_id, :local_date],
        name: "classroom_attendance_day_idx"
      )
    )

    drop_if_exists(constraint(:classroom_attendance_submissions, :classroom_attendance_marks))

    drop_if_exists(constraint(:classroom_attendance_submissions, :classroom_attendance_roster))

    drop_if_exists(constraint(:classroom_attendance_submissions, :classroom_attendance_revision))

    drop_if_exists(constraint(:classroom_attendance_submissions, :classroom_attendance_basis))

    drop(
      constraint(
        :classroom_attendance_submissions,
        "classroom_attendance_submissions_class_id_fkey"
      )
    )

    drop(table(:classroom_attendance_submissions))

    drop_if_exists(
      constraint(:platform_outbox_events, :platform_outbox_classification_domain_boundary)
    )

    create constraint(:platform_outbox_events, :platform_outbox_classification_domain_boundary,
             check: """
               (classification = 'internal' AND aggregate_type NOT LIKE 'people.core.%' AND aggregate_type NOT LIKE 'classroom.core.%') OR (classification = 'restricted' AND aggregate_type IN ('people.core.person', 'people.core.participation', 'people.core.account') AND event_type LIKE 'people.core.%') OR (classification = 'restricted' AND aggregate_type IN ('classroom.core.class', 'classroom.core.enrolment', 'classroom.core.assignment', 'classroom.core.placement') AND event_type LIKE 'classroom.core.%')
             """
           )

    drop_if_exists(
      index(:classroom_attendance_exposures, [:tenant_id, :actor_id, :day],
        name: "classroom_attendance_exposure_day_idx"
      )
    )

    drop_if_exists(
      constraint(:classroom_attendance_exposures, :classroom_attendance_person_budget)
    )

    drop_if_exists(
      constraint(:classroom_attendance_exposures, :classroom_attendance_class_budget)
    )

    drop(table(:classroom_attendance_exposures))
  end
end
