defmodule Chimwemwe.Repo.Migrations.AddOrganizationLegalStructureFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:organization_legal_entity_consolidation_parentages, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :child_legal_entity_id,
        references(:organization_legal_entities,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "organization_legal_consolidation_child_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :parent_legal_entity_id,
        references(:organization_legal_entities,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "organization_legal_consolidation_parent_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:reporting_basis, :text, null: false, default: "management_reporting")
      add(:effective_from, :date, null: false)
      add(:evidence_reference, :text, null: false)
      add(:status, :text, null: false, default: "active")
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(
             :organization_legal_entity_consolidation_parentages,
             :organization_legal_consolidation_distinct_entities,
             check: """
               child_legal_entity_id <> parent_legal_entity_id
             """
           )

    create constraint(
             :organization_legal_entity_consolidation_parentages,
             :organization_legal_consolidation_basis_allowed,
             check: """
               reporting_basis IN ('management_reporting')
             """
           )

    create constraint(
             :organization_legal_entity_consolidation_parentages,
             :organization_legal_consolidation_status_allowed,
             check: """
               status IN ('active')
             """
           )

    create constraint(
             :organization_legal_entity_consolidation_parentages,
             :organization_legal_consolidation_lock_version_positive,
             check: """
               lock_version >= 1
             """
           )

    create constraint(
             :organization_legal_entity_consolidation_parentages,
             :organization_legal_consolidation_evidence_reference_length,
             check: """
               char_length(evidence_reference) BETWEEN 1 AND 120
             """
           )

    create index(:organization_legal_entity_consolidation_parentages, [:id, :tenant_id],
             name: "organization_legal_consolidation_id_tenant_index",
             unique: true
           )

    create index(
             :organization_legal_entity_consolidation_parentages,
             [:tenant_id, :child_legal_entity_id],
             name: "organization_legal_consolidation_active_child_index",
             unique: true
           )

    create index(
             :organization_legal_entity_consolidation_parentages,
             [:tenant_id, :parent_legal_entity_id, :child_legal_entity_id],
             name: "organization_legal_consolidation_parent_index"
           )

    create table(:organization_legal_corporate_units, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :legal_entity_id,
        references(:organization_legal_entities,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "organization_legal_corporate_units_entity_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      # The reviewed composite self-reference is added after its destination
      # unique index exists. PostgreSQL cannot create it inline before then.
      add(:parent_corporate_unit_id, :uuid)

      add(:status, :text, null: false, default: "active")
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(
             :organization_legal_corporate_units,
             :organization_legal_corporate_units_not_self_parented,
             check: """
               parent_corporate_unit_id IS NULL OR id <> parent_corporate_unit_id
             """
           )

    create constraint(
             :organization_legal_corporate_units,
             :organization_legal_corporate_units_status_allowed,
             check: """
               status IN ('active')
             """
           )

    create constraint(
             :organization_legal_corporate_units,
             :organization_legal_corporate_units_lock_version_positive,
             check: """
               lock_version >= 1
             """
           )

    create index(:organization_legal_corporate_units, [:id, :tenant_id],
             name: "organization_legal_corporate_units_id_tenant_index",
             unique: true
           )

    create index(:organization_legal_corporate_units, [:id, :tenant_id, :legal_entity_id],
             name: "organization_legal_corporate_units_identity_owner_index",
             unique: true
           )

    execute("""
    ALTER TABLE organization_legal_corporate_units
    ADD CONSTRAINT organization_legal_corporate_units_parent_owner_fkey
    FOREIGN KEY (parent_corporate_unit_id, legal_entity_id, tenant_id)
    REFERENCES organization_legal_corporate_units (id, legal_entity_id, tenant_id)
    MATCH SIMPLE
    ON DELETE RESTRICT
    """)

    create index(
             :organization_legal_corporate_units,
             [:tenant_id, :legal_entity_id, :parent_corporate_unit_id, :id],
             name: "organization_legal_corporate_units_parent_index"
           )

    create table(:organization_legal_entity_relationships, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :source_legal_entity_id,
        references(:organization_legal_entities,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "organization_legal_relationships_source_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :target_legal_entity_id,
        references(:organization_legal_entities,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "organization_legal_relationships_target_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:relationship_type, :text, null: false)
      add(:basis_key, :text, null: false)
      add(:interest_bps, :bigint)
      add(:effective_from, :date, null: false)
      add(:evidence_reference, :text, null: false)
      add(:status, :text, null: false, default: "active")
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(
             :organization_legal_entity_relationships,
             :organization_legal_relationships_type_allowed,
             check: """
               relationship_type IN (
               'equity_interest',
               'governing_body_appointment',
               'statutory_control',
               'contractual_control'
             )

             """
           )

    create constraint(
             :organization_legal_entity_relationships,
             :organization_legal_relationships_interest_consistent,
             check: """
               (relationship_type = 'equity_interest' AND interest_bps BETWEEN 1 AND 10000) OR
             (relationship_type <> 'equity_interest' AND interest_bps IS NULL)

             """
           )

    create constraint(
             :organization_legal_entity_relationships,
             :organization_legal_relationships_basis_consistent,
             check: """
               (relationship_type = 'equity_interest' AND basis_key = 'registered_equity') OR
             (relationship_type = 'governing_body_appointment' AND basis_key = 'governing_instrument') OR
             (relationship_type = 'statutory_control' AND basis_key = 'statute') OR
             (relationship_type = 'contractual_control' AND basis_key = 'contract')

             """
           )

    create constraint(
             :organization_legal_entity_relationships,
             :organization_legal_relationships_distinct_endpoints,
             check: """
               source_legal_entity_id <> target_legal_entity_id
             """
           )

    create constraint(
             :organization_legal_entity_relationships,
             :organization_legal_relationships_status_allowed,
             check: """
               status IN ('active')
             """
           )

    create constraint(
             :organization_legal_entity_relationships,
             :organization_legal_relationships_lock_version_positive,
             check: """
               lock_version >= 1
             """
           )

    create constraint(
             :organization_legal_entity_relationships,
             :organization_legal_relationships_evidence_reference_length,
             check: """
               char_length(evidence_reference) BETWEEN 1 AND 120
             """
           )

    create index(:organization_legal_entity_relationships, [:id, :tenant_id],
             name: "organization_legal_relationships_id_tenant_index",
             unique: true
           )

    create index(
             :organization_legal_entity_relationships,
             [
               :tenant_id,
               :source_legal_entity_id,
               :target_legal_entity_id,
               :relationship_type,
               :effective_from
             ],
             name: "organization_legal_relationships_direct_fact_index",
             unique: true
           )

    create index(
             :organization_legal_entity_relationships,
             [:tenant_id, :source_legal_entity_id, :relationship_type, :id],
             name: "organization_legal_relationships_source_index"
           )

    create index(
             :organization_legal_entity_relationships,
             [:tenant_id, :target_legal_entity_id, :relationship_type, :id],
             name: "organization_legal_relationships_target_index"
           )

    create table(:organization_legal_corporate_unit_profile_revisions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :corporate_unit_id,
        references(:organization_legal_corporate_units,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "organization_legal_corporate_unit_profiles_unit_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:revision_number, :bigint, null: false)
      add(:official_name, :text, null: false)
      add(:display_name, :text, null: false)
      add(:recorded_by_actor_id, :uuid, null: false)
      add(:recorded_at, :utc_datetime_usec, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(
             :organization_legal_corporate_unit_profile_revisions,
             :organization_legal_corporate_unit_profiles_revision_positive,
             check: """
               revision_number >= 1
             """
           )

    create constraint(
             :organization_legal_corporate_unit_profile_revisions,
             :organization_legal_corporate_unit_profiles_official_name_length,
             check: """
               char_length(official_name) BETWEEN 1 AND 200
             """
           )

    create constraint(
             :organization_legal_corporate_unit_profile_revisions,
             :organization_legal_corporate_unit_profiles_display_name_length,
             check: """
               char_length(display_name) BETWEEN 1 AND 200
             """
           )

    create index(:organization_legal_corporate_unit_profile_revisions, [:id, :tenant_id],
             name: "organization_legal_corporate_unit_profiles_id_tenant_index",
             unique: true
           )

    create index(
             :organization_legal_corporate_unit_profile_revisions,
             [:tenant_id, :corporate_unit_id, :revision_number],
             name: "organization_legal_corporate_unit_profiles_revision_index",
             unique: true
           )

    execute("""
    CREATE FUNCTION organization_legal_reject_structure_fact_mutation()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      RAISE EXCEPTION USING
        ERRCODE = '23514',
        MESSAGE = 'organization legal structure facts are immutable in Slice 2.1-C1';
    END;
    $$;
    """)

    for {trigger, table} <- [
          {"organization_legal_relationships_immutable",
           "organization_legal_entity_relationships"},
          {"organization_legal_consolidation_parentages_immutable",
           "organization_legal_entity_consolidation_parentages"},
          {"organization_legal_corporate_units_immutable", "organization_legal_corporate_units"},
          {"organization_legal_corporate_unit_profiles_immutable",
           "organization_legal_corporate_unit_profile_revisions"}
        ] do
      execute("""
      CREATE TRIGGER #{trigger}
      BEFORE UPDATE OR DELETE
      ON #{table}
      FOR EACH ROW
      EXECUTE FUNCTION organization_legal_reject_structure_fact_mutation();
      """)
    end
  end

  def down do
    execute("""
    DO $$
    BEGIN
      IF EXISTS (SELECT 1 FROM organization_legal_entity_relationships)
         OR EXISTS (SELECT 1 FROM organization_legal_entity_consolidation_parentages)
         OR EXISTS (SELECT 1 FROM organization_legal_corporate_units)
         OR EXISTS (SELECT 1 FROM organization_legal_corporate_unit_profile_revisions)
         OR EXISTS (
           SELECT 1
           FROM platform_authority_audit_events
           WHERE action_name IN (
             'organization.legal.relationship.establish',
             'organization.legal.consolidation_parent.set',
             'organization.legal.corporate_unit.register'
           )
         )
         OR EXISTS (
           SELECT 1
           FROM platform_outbox_events
           WHERE aggregate_type IN (
             'organization.legal.relationship',
             'organization.legal.consolidation_parentage',
             'organization.legal.corporate_unit'
           )
         )
         OR EXISTS (
           SELECT 1
           FROM platform_authority_action_idempotency
           WHERE action_name IN (
             'organization.legal.relationship.establish',
             'organization.legal.consolidation_parent.set',
             'organization.legal.corporate_unit.register'
           )
         )
      THEN
        RAISE EXCEPTION
          'organization.legal structure rollback requires empty state and durable evidence';
      END IF;
    END
    $$;
    """)

    drop_if_exists(
      index(
        :organization_legal_corporate_unit_profile_revisions,
        [:tenant_id, :corporate_unit_id, :revision_number],
        name: "organization_legal_corporate_unit_profiles_revision_index"
      )
    )

    drop_if_exists(
      index(:organization_legal_corporate_unit_profile_revisions, [:id, :tenant_id],
        name: "organization_legal_corporate_unit_profiles_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_corporate_unit_profile_revisions,
        :organization_legal_corporate_unit_profiles_display_name_length
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_corporate_unit_profile_revisions,
        :organization_legal_corporate_unit_profiles_official_name_length
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_corporate_unit_profile_revisions,
        :organization_legal_corporate_unit_profiles_revision_positive
      )
    )

    drop(
      constraint(
        :organization_legal_corporate_unit_profile_revisions,
        "organization_legal_corporate_unit_profiles_unit_tenant_fkey"
      )
    )

    drop(table(:organization_legal_corporate_unit_profile_revisions))

    drop_if_exists(
      index(
        :organization_legal_entity_relationships,
        [:tenant_id, :target_legal_entity_id, :relationship_type, :id],
        name: "organization_legal_relationships_target_index"
      )
    )

    drop_if_exists(
      index(
        :organization_legal_entity_relationships,
        [:tenant_id, :source_legal_entity_id, :relationship_type, :id],
        name: "organization_legal_relationships_source_index"
      )
    )

    drop_if_exists(
      index(
        :organization_legal_entity_relationships,
        [
          :tenant_id,
          :source_legal_entity_id,
          :target_legal_entity_id,
          :relationship_type,
          :effective_from
        ],
        name: "organization_legal_relationships_direct_fact_index"
      )
    )

    drop_if_exists(
      index(:organization_legal_entity_relationships, [:id, :tenant_id],
        name: "organization_legal_relationships_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_entity_relationships,
        :organization_legal_relationships_evidence_reference_length
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_entity_relationships,
        :organization_legal_relationships_lock_version_positive
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_entity_relationships,
        :organization_legal_relationships_status_allowed
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_entity_relationships,
        :organization_legal_relationships_distinct_endpoints
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_entity_relationships,
        :organization_legal_relationships_basis_consistent
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_entity_relationships,
        :organization_legal_relationships_interest_consistent
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_entity_relationships,
        :organization_legal_relationships_type_allowed
      )
    )

    drop(
      constraint(
        :organization_legal_entity_relationships,
        "organization_legal_relationships_target_tenant_fkey"
      )
    )

    drop(
      constraint(
        :organization_legal_entity_relationships,
        "organization_legal_relationships_source_tenant_fkey"
      )
    )

    drop(table(:organization_legal_entity_relationships))

    drop_if_exists(
      index(
        :organization_legal_corporate_units,
        [:tenant_id, :legal_entity_id, :parent_corporate_unit_id, :id],
        name: "organization_legal_corporate_units_parent_index"
      )
    )

    drop_if_exists(
      index(:organization_legal_corporate_units, [:id, :tenant_id, :legal_entity_id],
        name: "organization_legal_corporate_units_identity_owner_index"
      )
    )

    drop_if_exists(
      index(:organization_legal_corporate_units, [:id, :tenant_id],
        name: "organization_legal_corporate_units_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_corporate_units,
        :organization_legal_corporate_units_lock_version_positive
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_corporate_units,
        :organization_legal_corporate_units_status_allowed
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_corporate_units,
        :organization_legal_corporate_units_not_self_parented
      )
    )

    drop(
      constraint(
        :organization_legal_corporate_units,
        "organization_legal_corporate_units_parent_owner_fkey"
      )
    )

    drop(
      constraint(
        :organization_legal_corporate_units,
        "organization_legal_corporate_units_entity_tenant_fkey"
      )
    )

    drop(table(:organization_legal_corporate_units))

    drop_if_exists(
      index(
        :organization_legal_entity_consolidation_parentages,
        [:tenant_id, :parent_legal_entity_id, :child_legal_entity_id],
        name: "organization_legal_consolidation_parent_index"
      )
    )

    drop_if_exists(
      index(
        :organization_legal_entity_consolidation_parentages,
        [:tenant_id, :child_legal_entity_id],
        name: "organization_legal_consolidation_active_child_index"
      )
    )

    drop_if_exists(
      index(:organization_legal_entity_consolidation_parentages, [:id, :tenant_id],
        name: "organization_legal_consolidation_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_entity_consolidation_parentages,
        :organization_legal_consolidation_evidence_reference_length
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_entity_consolidation_parentages,
        :organization_legal_consolidation_lock_version_positive
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_entity_consolidation_parentages,
        :organization_legal_consolidation_status_allowed
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_entity_consolidation_parentages,
        :organization_legal_consolidation_basis_allowed
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_entity_consolidation_parentages,
        :organization_legal_consolidation_distinct_entities
      )
    )

    drop(
      constraint(
        :organization_legal_entity_consolidation_parentages,
        "organization_legal_consolidation_parent_tenant_fkey"
      )
    )

    drop(
      constraint(
        :organization_legal_entity_consolidation_parentages,
        "organization_legal_consolidation_child_tenant_fkey"
      )
    )

    drop(table(:organization_legal_entity_consolidation_parentages))

    execute("DROP FUNCTION IF EXISTS organization_legal_reject_structure_fact_mutation()")
  end
end
