defmodule Chimwemwe.Repo.Migrations.AuthorityRoleAssignment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:platform_actor_role_assignments) do
      add(:lock_version, :bigint, null: false, default: 1)
    end

    create constraint(
             :platform_actor_role_assignments,
             :platform_actor_role_assignment_version_must_be_positive,
             check: """
               lock_version >= 1
             """
           )

    alter table(:platform_authority_action_idempotency) do
      add(:result_payload, :map)
    end

    drop_if_exists(
      constraint(
        :platform_authority_action_idempotency,
        :platform_authority_idempotency_completion_must_be_consistent
      )
    )

    create constraint(
             :platform_authority_action_idempotency,
             :platform_authority_idempotency_completion_must_be_consistent,
             check: """
               (status = 'started' AND result_name IS NULL AND result_lock_version IS NULL AND
               result_payload IS NULL AND
               audit_reference IS NULL AND event_id IS NULL AND completed_at IS NULL) OR
             (status = 'completed' AND audit_reference IS NOT NULL AND event_id IS NOT NULL AND
               completed_at IS NOT NULL AND (
                 (result_payload IS NULL AND result_name IS NOT NULL AND result_lock_version IS NOT NULL) OR
                 (result_payload IS NOT NULL AND result_name IS NULL AND result_lock_version IS NULL)
               ))

             """
           )

    create constraint(
             :platform_authority_action_idempotency,
             :platform_authority_idempotency_payload_must_be_an_object,
             check: """
               result_payload IS NULL OR jsonb_typeof(result_payload) = 'object'
             """
           )

    drop_if_exists(
      constraint(
        :platform_authority_audit_events,
        :platform_authority_audit_versions_must_be_consecutive
      )
    )

    create constraint(
             :platform_authority_audit_events,
             :platform_authority_audit_versions_must_be_consecutive,
             check: """
               before_version >= 0 AND after_version = before_version + 1
             """
           )
  end

  def down do
    drop_if_exists(
      constraint(
        :platform_authority_audit_events,
        :platform_authority_audit_versions_must_be_consecutive
      )
    )

    create constraint(
             :platform_authority_audit_events,
             :platform_authority_audit_versions_must_be_consecutive,
             check: """
               before_version >= 1 AND after_version = before_version + 1
             """
           )

    drop_if_exists(
      constraint(
        :platform_authority_action_idempotency,
        :platform_authority_idempotency_payload_must_be_an_object
      )
    )

    drop_if_exists(
      constraint(
        :platform_authority_action_idempotency,
        :platform_authority_idempotency_completion_must_be_consistent
      )
    )

    create constraint(
             :platform_authority_action_idempotency,
             :platform_authority_idempotency_completion_must_be_consistent,
             check: """
               (status = 'started' AND result_name IS NULL AND result_lock_version IS NULL AND
               audit_reference IS NULL AND event_id IS NULL AND completed_at IS NULL) OR
             (status = 'completed' AND result_name IS NOT NULL AND result_lock_version IS NOT NULL AND
               audit_reference IS NOT NULL AND event_id IS NOT NULL AND completed_at IS NOT NULL)

             """
           )

    alter table(:platform_authority_action_idempotency) do
      remove(:result_payload)
    end

    drop_if_exists(
      constraint(
        :platform_actor_role_assignments,
        :platform_actor_role_assignment_version_must_be_positive
      )
    )

    alter table(:platform_actor_role_assignments) do
      remove(:lock_version)
    end
  end
end
