defmodule Chimwemwe.Repo.Migrations.Phase2TemporalCompletion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DROP TRIGGER platform_temporal_qualification_fact_guard
      ON platform_temporal_qualification_facts;
    """)

    execute("""
    DROP FUNCTION guard_platform_temporal_qualification_fact();
    """)

    execute("""
    DROP TRIGGER platform_temporal_qualification_segment_guard
      ON platform_temporal_qualification_segments;
    """)

    execute("""
    DROP FUNCTION guard_platform_temporal_qualification_segment();
    """)

    create table(:platform_temporal_qualification_current_projections, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:aggregate_id, :uuid, null: false)
      add(:revision_id, :uuid, null: false)
      add(:projection_version, :bigint, null: false)
      add(:segment_count, :bigint, null: false)
      add(:refreshed_at, :utc_datetime_usec, null: false)
    end

    create index(:platform_temporal_qualification_current_projections, [:id, :tenant_id],
             name: "platform_temporal_current_projections_id_tenant_index",
             unique: true
           )

    create index(
             :platform_temporal_qualification_current_projections,
             [:tenant_id, :aggregate_id],
             name: "platform_temporal_current_projections_aggregate_index",
             unique: true
           )

    alter table(:platform_temporal_qualification_facts) do
      add(:redacted_at, :utc_datetime_usec)
      add(:redaction_receipt_id, :uuid)
    end

    drop_if_exists(
      constraint(:platform_temporal_qualification_facts, :platform_temporal_fact_quantity_nonzero)
    )

    create constraint(
             :platform_temporal_qualification_facts,
             :platform_temporal_fact_redaction_shape,
             check: """
               (redacted_at IS NULL AND redaction_receipt_id IS NULL AND quantity <> 0) OR
             (redacted_at IS NOT NULL AND redaction_receipt_id IS NOT NULL AND quantity = 0)

             """
           )

    execute("""
    CREATE FUNCTION guard_platform_temporal_qualification_fact()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      operation_kind text;
      operation_target uuid;
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_fact_delete_forbidden',
          MESSAGE = 'temporal qualification fact deletion is forbidden';
      END IF;

      IF TG_OP = 'UPDATE' AND NOT (
        OLD.redacted_at IS NULL
        AND NEW.redacted_at IS NOT NULL
        AND NEW.redaction_receipt_id IS NOT NULL
        AND NEW.quantity = 0
        AND NEW.id = OLD.id
        AND NEW.tenant_id = OLD.tenant_id
        AND NEW.scope_id = OLD.scope_id
        AND NEW.operation_id = OLD.operation_id
        AND NEW.kind = OLD.kind
        AND NEW.reverses_fact_id IS NOT DISTINCT FROM OLD.reverses_fact_id
        AND NEW.effective_on = OLD.effective_on
        AND NEW.recorded_at = OLD.recorded_at
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_fact_immutable',
          MESSAGE = 'temporal qualification facts are immutable';
      END IF;

      IF TG_OP = 'INSERT' THEN
        NEW.recorded_at := transaction_timestamp() AT TIME ZONE 'UTC';
      END IF;

      IF TG_OP = 'INSERT' THEN
        SELECT kind, target_fact_id
        INTO operation_kind, operation_target
        FROM platform_temporal_qualification_fact_operations
        WHERE id = NEW.operation_id
          AND tenant_id = NEW.tenant_id
          AND scope_id = NEW.scope_id;

        IF operation_kind IS NULL THEN
          RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'platform_temporal_fact_operation_missing',
            MESSAGE = 'temporal qualification fact operation is missing';
        END IF;

        IF operation_kind = 'record' AND (
          NEW.kind <> 'entry'
          OR EXISTS (
            SELECT 1
            FROM platform_temporal_qualification_facts
            WHERE tenant_id = NEW.tenant_id
              AND operation_id = NEW.operation_id
          )
        ) THEN
          RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'platform_temporal_fact_record_shape',
            MESSAGE = 'record operation must create exactly one entry';
        END IF;

        IF operation_kind = 'reverse_and_replace' AND (
          (NEW.kind = 'reversal' AND (
            NEW.reverses_fact_id IS DISTINCT FROM operation_target
            OR EXISTS (
              SELECT 1
              FROM platform_temporal_qualification_facts
              WHERE tenant_id = NEW.tenant_id
                AND operation_id = NEW.operation_id
                AND kind = 'reversal'
            )
          ))
          OR
          (NEW.kind = 'entry' AND EXISTS (
            SELECT 1
            FROM platform_temporal_qualification_facts
            WHERE tenant_id = NEW.tenant_id
              AND operation_id = NEW.operation_id
              AND kind = 'entry'
          ))
        ) THEN
          RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'platform_temporal_fact_correction_shape',
            MESSAGE = 'correction operation fact shape is invalid';
        END IF;

        IF NEW.kind = 'reversal' AND NOT EXISTS (
          SELECT 1
          FROM platform_temporal_qualification_facts
          WHERE id = NEW.reverses_fact_id
            AND tenant_id = NEW.tenant_id
            AND scope_id = NEW.scope_id
            AND kind = 'entry'
        ) THEN
          RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'platform_temporal_qualification_fact_reversal_target',
            MESSAGE = 'temporal qualification reversal target is invalid';
        END IF;
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    create table(:platform_temporal_qualification_import_records, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:import_id, :uuid, null: false)
      add(:version, :bigint, null: false)
      add(:predecessor_record_id, :uuid)
      add(:module_key, :text, null: false)
      add(:state, :text, null: false)
      add(:conflict_code, :text)
      add(:source_snapshot_digest, :binary, null: false)
      add(:source_identifier_digest, :binary, null: false)
      add(:mapping_revision, :text, null: false)
      add(:aggregate_id, :uuid)
      add(:revision_id, :uuid)
      add(:recorded_at, :utc_datetime_usec, null: false)
    end

    create constraint(
             :platform_temporal_qualification_import_records,
             :platform_temporal_import_digest_shape,
             check: """
               octet_length(source_snapshot_digest) = 32 AND octet_length(source_identifier_digest) = 32
             """
           )

    create constraint(
             :platform_temporal_qualification_import_records,
             :platform_temporal_import_mapping_revision_shape,
             check: """
               char_length(mapping_revision) BETWEEN 1 AND 80 AND mapping_revision ~ '^[A-Za-z0-9][A-Za-z0-9._-]*$'
             """
           )

    create constraint(
             :platform_temporal_qualification_import_records,
             :platform_temporal_import_state_shape,
             check: """
               (state = 'baseline' AND conflict_code IS NULL AND aggregate_id IS NOT NULL AND revision_id IS NOT NULL AND predecessor_record_id IS NULL AND version = 1) OR
             (state = 'reconciliation_required' AND conflict_code IS NOT NULL AND aggregate_id IS NULL AND revision_id IS NULL AND predecessor_record_id IS NULL AND version = 1) OR
             (state = 'reconciled' AND conflict_code IS NULL AND aggregate_id IS NOT NULL AND revision_id IS NOT NULL AND predecessor_record_id IS NOT NULL AND version = 2)

             """
           )

    create index(:platform_temporal_qualification_import_records, [:id, :tenant_id],
             name: "platform_temporal_import_records_id_tenant_index",
             unique: true
           )

    create index(
             :platform_temporal_qualification_import_records,
             [:tenant_id, :import_id, :version],
             name: "platform_temporal_import_records_version_index",
             unique: true
           )

    create index(
             :platform_temporal_qualification_import_records,
             [:tenant_id, :source_snapshot_digest, :source_identifier_digest, :mapping_revision],
             name: "platform_temporal_import_records_source_index",
             unique: true,
             where: "version = 1"
           )

    create index(
             :platform_temporal_qualification_import_records,
             [:tenant_id, :predecessor_record_id],
             name: "platform_temporal_import_records_successor_index",
             unique: true,
             where: "predecessor_record_id IS NOT NULL"
           )

    execute("""
    CREATE FUNCTION guard_platform_temporal_import_record()
    RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE
      predecessor_state text;
      predecessor_import uuid;
    BEGIN
      IF TG_OP IN ('UPDATE', 'DELETE') THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_import_record_immutable',
          MESSAGE = 'temporal import provenance is immutable';
      END IF;

      NEW.recorded_at := transaction_timestamp() AT TIME ZONE 'UTC';

      IF NEW.aggregate_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM platform_temporal_qualification_revisions
        WHERE tenant_id = NEW.tenant_id AND aggregate_id = NEW.aggregate_id AND id = NEW.revision_id
      ) THEN
        RAISE EXCEPTION USING ERRCODE = '23503',
          CONSTRAINT = 'platform_temporal_import_target_missing',
          MESSAGE = 'temporal import target revision is missing';
      END IF;

      IF NEW.predecessor_record_id IS NOT NULL THEN
        SELECT state, import_id INTO predecessor_state, predecessor_import
        FROM platform_temporal_qualification_import_records
        WHERE tenant_id = NEW.tenant_id AND id = NEW.predecessor_record_id;

        IF predecessor_state IS DISTINCT FROM 'reconciliation_required'
           OR predecessor_import IS DISTINCT FROM NEW.import_id THEN
          RAISE EXCEPTION USING ERRCODE = '23514',
            CONSTRAINT = 'platform_temporal_import_predecessor_invalid',
            MESSAGE = 'temporal import reconciliation predecessor is invalid';
        END IF;
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER platform_temporal_import_record_guard
    BEFORE INSERT OR UPDATE OR DELETE ON platform_temporal_qualification_import_records
    FOR EACH ROW EXECUTE FUNCTION guard_platform_temporal_import_record();
    """)

    create table(:platform_temporal_qualification_retention_controls, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:aggregate_id, :uuid, null: false)
      add(:scope_id, :uuid, null: false)
      add(:module_key, :text, null: false)
      add(:policy_key, :text, null: false)
      add(:classification, :text, null: false)
      add(:retention_started_on, :date, null: false)
      add(:retain_until, :date, null: false)
      add(:state, :text, null: false)
      add(:version, :bigint, null: false)
      add(:active_hold_digest, :binary)
      add(:current_receipt_id, :uuid, null: false)
      add(:erased_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(
             :platform_temporal_qualification_retention_controls,
             :platform_temporal_retention_module_key_shape,
             check: """
               char_length(module_key) BETWEEN 3 AND 120 AND
             module_key ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$'

             """
           )

    create constraint(
             :platform_temporal_qualification_retention_controls,
             :platform_temporal_retention_policy_key_shape,
             check: """
               char_length(policy_key) BETWEEN 3 AND 120 AND
             policy_key ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$'

             """
           )

    create constraint(
             :platform_temporal_qualification_retention_controls,
             :platform_temporal_retention_window_valid,
             check: """
               retention_started_on <= retain_until
             """
           )

    create constraint(
             :platform_temporal_qualification_retention_controls,
             :platform_temporal_retention_state_shape,
             check: """
               (state = 'retained' AND active_hold_digest IS NULL AND erased_at IS NULL) OR
             (state = 'held' AND octet_length(active_hold_digest) = 32 AND erased_at IS NULL) OR
             (state = 'erased' AND active_hold_digest IS NULL AND erased_at IS NOT NULL)

             """
           )

    create index(:platform_temporal_qualification_retention_controls, [:id, :tenant_id],
             name: "platform_temporal_retention_controls_id_tenant_index",
             unique: true
           )

    create index(:platform_temporal_qualification_retention_controls, [:tenant_id, :aggregate_id],
             name: "platform_temporal_retention_controls_aggregate_index",
             unique: true
           )

    create index(
             :platform_temporal_qualification_retention_controls,
             [:tenant_id, :module_key, :state],
             name: "platform_temporal_retention_controls_module_state_index"
           )

    create table(:platform_temporal_qualification_retention_receipts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:control_id, :uuid, null: false)
      add(:aggregate_id, :uuid, null: false)
      add(:scope_id, :uuid, null: false)
      add(:operation, :text, null: false)
      add(:version, :bigint, null: false)
      add(:reason_code, :text, null: false)
      add(:hold_reference_digest, :binary)
      add(:redacted_segment_count, :bigint, null: false, default: 0)
      add(:redacted_fact_count, :bigint, null: false, default: 0)
      add(:purged_projection_count, :bigint, null: false, default: 0)
      add(:recorded_at, :utc_datetime_usec, null: false)
    end

    create constraint(
             :platform_temporal_qualification_retention_receipts,
             :platform_temporal_retention_receipt_reason_shape,
             check: """
               char_length(reason_code) BETWEEN 1 AND 80 AND reason_code ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*$'
             """
           )

    create constraint(
             :platform_temporal_qualification_retention_receipts,
             :platform_temporal_retention_receipt_operation_shape,
             check: """
               (operation IN ('declared', 'erased') AND hold_reference_digest IS NULL) OR
             (operation IN ('hold_placed', 'hold_released') AND octet_length(hold_reference_digest) = 32)

             """
           )

    create index(:platform_temporal_qualification_retention_receipts, [:id, :tenant_id],
             name: "platform_temporal_retention_receipts_id_tenant_index",
             unique: true
           )

    create index(
             :platform_temporal_qualification_retention_receipts,
             [:tenant_id, :control_id, :version],
             name: "platform_temporal_retention_receipts_version_index",
             unique: true
           )

    execute("""
    CREATE FUNCTION guard_platform_temporal_retention_receipt()
    RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP IN ('UPDATE', 'DELETE') THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_retention_receipt_immutable',
          MESSAGE = 'temporal retention receipts are immutable';
      END IF;
      NEW.recorded_at := transaction_timestamp() AT TIME ZONE 'UTC';
      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER platform_temporal_retention_receipt_guard
    BEFORE INSERT OR UPDATE OR DELETE ON platform_temporal_qualification_retention_receipts
    FOR EACH ROW EXECUTE FUNCTION guard_platform_temporal_retention_receipt();
    """)

    alter table(:platform_temporal_qualification_segments) do
      add(:redacted_at, :utc_datetime_usec)
      add(:redaction_receipt_id, :uuid)
    end

    create constraint(
             :platform_temporal_qualification_segments,
             :platform_temporal_segment_redaction_shape,
             check: """
               (redacted_at IS NULL AND redaction_receipt_id IS NULL AND value <> '[redacted]') OR
             (redacted_at IS NOT NULL AND redaction_receipt_id IS NOT NULL AND value = '[redacted]')

             """
           )

    execute("""
    CREATE FUNCTION guard_platform_temporal_qualification_segment()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_segment_delete_forbidden',
          MESSAGE = 'temporal qualification segment deletion is forbidden';
      END IF;

      IF TG_OP = 'UPDATE' AND NOT (
        OLD.redacted_at IS NULL
        AND NEW.redacted_at IS NOT NULL
        AND NEW.redaction_receipt_id IS NOT NULL
        AND NEW.value = '[redacted]'
        AND NEW.id = OLD.id
        AND NEW.tenant_id = OLD.tenant_id
        AND NEW.aggregate_id = OLD.aggregate_id
        AND NEW.revision_id = OLD.revision_id
        AND NEW.effective_from = OLD.effective_from
        AND NEW.effective_until = OLD.effective_until
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_segment_immutable',
          MESSAGE = 'temporal qualification segments are immutable';
      END IF;

      PERFORM pg_advisory_xact_lock(
        hashtextextended(
          'platform-temporal-qualification-segment:' ||
            NEW.tenant_id::text || ':' || NEW.revision_id::text,
          0
        )
      );

      IF EXISTS (
        SELECT 1
        FROM platform_temporal_qualification_segments AS segment
        WHERE segment.tenant_id = NEW.tenant_id
          AND segment.revision_id = NEW.revision_id
          AND segment.id <> NEW.id
          AND NEW.effective_from < segment.effective_until
          AND segment.effective_from < NEW.effective_until
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23P01',
          CONSTRAINT = 'platform_temporal_qualification_segment_no_overlap',
          MESSAGE = 'temporal qualification segments overlap';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER platform_temporal_qualification_fact_guard
    BEFORE INSERT OR UPDATE OR DELETE
    ON platform_temporal_qualification_facts
    FOR EACH ROW
    EXECUTE FUNCTION guard_platform_temporal_qualification_fact();
    """)

    execute("""
    CREATE TRIGGER platform_temporal_qualification_segment_guard
    BEFORE INSERT OR UPDATE OR DELETE
    ON platform_temporal_qualification_segments
    FOR EACH ROW
    EXECUTE FUNCTION guard_platform_temporal_qualification_segment();
    """)

    create index(
             :platform_temporal_qualification_retention_controls,
             [:id, :tenant_id, :aggregate_id],
             name: "platform_temporal_retention_controls_scope_reference_index",
             unique: true
           )

    create index(
             :platform_temporal_qualification_retention_receipts,
             [:id, :tenant_id, :control_id],
             name: "platform_temporal_retention_receipts_control_reference_index",
             unique: true
           )

    execute("""
    ALTER TABLE platform_temporal_qualification_current_projections
      ADD CONSTRAINT platform_temporal_current_projection_aggregate_tenant_fkey
      FOREIGN KEY (aggregate_id, tenant_id)
      REFERENCES platform_temporal_qualification_aggregates (id, tenant_id)
      ON DELETE CASCADE NOT VALID,
      ADD CONSTRAINT platform_temporal_current_projection_revision_tenant_fkey
      FOREIGN KEY (revision_id, tenant_id, aggregate_id)
      REFERENCES platform_temporal_qualification_revisions (id, tenant_id, aggregate_id)
      ON DELETE CASCADE NOT VALID;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_import_records
      ADD CONSTRAINT platform_temporal_import_predecessor_tenant_fkey
      FOREIGN KEY (predecessor_record_id, tenant_id)
      REFERENCES platform_temporal_qualification_import_records (id, tenant_id)
      ON DELETE RESTRICT NOT VALID,
      ADD CONSTRAINT platform_temporal_import_revision_tenant_fkey
      FOREIGN KEY (revision_id, tenant_id, aggregate_id)
      REFERENCES platform_temporal_qualification_revisions (id, tenant_id, aggregate_id)
      MATCH SIMPLE ON DELETE RESTRICT NOT VALID,
      ADD CONSTRAINT platform_temporal_import_module_tenant_fkey
      FOREIGN KEY (tenant_id, module_key)
      REFERENCES platform_module_entitlements (tenant_id, module_key)
      ON DELETE RESTRICT NOT VALID;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_retention_controls
      ADD CONSTRAINT platform_temporal_retention_aggregate_tenant_fkey
      FOREIGN KEY (aggregate_id, tenant_id, scope_id)
      REFERENCES platform_temporal_qualification_aggregates (id, tenant_id, scope_id)
      ON DELETE RESTRICT NOT VALID,
      ADD CONSTRAINT platform_temporal_retention_module_tenant_fkey
      FOREIGN KEY (tenant_id, module_key)
      REFERENCES platform_module_entitlements (tenant_id, module_key)
      ON DELETE RESTRICT NOT VALID;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_retention_receipts
      ADD CONSTRAINT platform_temporal_retention_receipt_control_tenant_fkey
      FOREIGN KEY (control_id, tenant_id, aggregate_id)
      REFERENCES platform_temporal_qualification_retention_controls (id, tenant_id, aggregate_id)
      ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED NOT VALID,
      ADD CONSTRAINT platform_temporal_retention_receipt_aggregate_tenant_fkey
      FOREIGN KEY (aggregate_id, tenant_id, scope_id)
      REFERENCES platform_temporal_qualification_aggregates (id, tenant_id, scope_id)
      ON DELETE RESTRICT NOT VALID;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_retention_controls
      ADD CONSTRAINT platform_temporal_retention_current_receipt_tenant_fkey
      FOREIGN KEY (current_receipt_id, tenant_id, id)
      REFERENCES platform_temporal_qualification_retention_receipts (id, tenant_id, control_id)
      ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED NOT VALID;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_segments
      ADD CONSTRAINT platform_temporal_segment_redaction_receipt_tenant_fkey
      FOREIGN KEY (redaction_receipt_id, tenant_id)
      REFERENCES platform_temporal_qualification_retention_receipts (id, tenant_id)
      MATCH SIMPLE ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED NOT VALID;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_facts
      ADD CONSTRAINT platform_temporal_fact_redaction_receipt_tenant_fkey
      FOREIGN KEY (redaction_receipt_id, tenant_id)
      REFERENCES platform_temporal_qualification_retention_receipts (id, tenant_id)
      MATCH SIMPLE ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED NOT VALID;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_current_projections
      VALIDATE CONSTRAINT platform_temporal_current_projection_aggregate_tenant_fkey,
      VALIDATE CONSTRAINT platform_temporal_current_projection_revision_tenant_fkey;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_import_records
      VALIDATE CONSTRAINT platform_temporal_import_predecessor_tenant_fkey,
      VALIDATE CONSTRAINT platform_temporal_import_revision_tenant_fkey,
      VALIDATE CONSTRAINT platform_temporal_import_module_tenant_fkey;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_retention_controls
      VALIDATE CONSTRAINT platform_temporal_retention_aggregate_tenant_fkey,
      VALIDATE CONSTRAINT platform_temporal_retention_module_tenant_fkey;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_retention_receipts
      VALIDATE CONSTRAINT platform_temporal_retention_receipt_control_tenant_fkey,
      VALIDATE CONSTRAINT platform_temporal_retention_receipt_aggregate_tenant_fkey;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_retention_controls
      VALIDATE CONSTRAINT platform_temporal_retention_current_receipt_tenant_fkey;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_segments
      VALIDATE CONSTRAINT platform_temporal_segment_redaction_receipt_tenant_fkey;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_facts
      VALIDATE CONSTRAINT platform_temporal_fact_redaction_receipt_tenant_fkey;
    """)
  end

  def down do
    execute("""
    DO $$
    BEGIN
      IF EXISTS (SELECT 1 FROM platform_temporal_qualification_retention_controls)
         OR EXISTS (SELECT 1 FROM platform_temporal_qualification_retention_receipts)
         OR EXISTS (SELECT 1 FROM platform_temporal_qualification_import_records)
         OR EXISTS (
           SELECT 1 FROM platform_temporal_qualification_segments
           WHERE redacted_at IS NOT NULL OR redaction_receipt_id IS NOT NULL
         )
         OR EXISTS (
           SELECT 1 FROM platform_temporal_qualification_facts
           WHERE redacted_at IS NOT NULL OR redaction_receipt_id IS NOT NULL
         )
         OR EXISTS (
           SELECT 1 FROM platform_authority_audit_events
           WHERE action_name LIKE 'platform.temporal_qualification.retention.%'
              OR action_name LIKE 'platform.temporal_qualification.legal_hold.%'
              OR action_name LIKE 'platform.temporal_qualification.import.%'
         )
         OR EXISTS (
           SELECT 1 FROM platform_outbox_events
           WHERE event_type LIKE 'platform.temporal_qualification.retention.%'
              OR event_type LIKE 'platform.temporal_qualification.legal_hold.%'
              OR event_type LIKE 'platform.temporal_qualification.import.%'
         )
         OR EXISTS (
           SELECT 1 FROM platform_authority_action_idempotency
           WHERE action_name LIKE 'platform.temporal_qualification.retention.%'
              OR action_name LIKE 'platform.temporal_qualification.legal_hold.%'
              OR action_name LIKE 'platform.temporal_qualification.import.%'
         )
      THEN
        RAISE EXCEPTION
          'temporal completion rollback requires no retained retention, import, redaction, or durable evidence state';
      END IF;
    END
    $$;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_facts
      DROP CONSTRAINT platform_temporal_fact_redaction_receipt_tenant_fkey;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_segments
      DROP CONSTRAINT platform_temporal_segment_redaction_receipt_tenant_fkey;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_retention_controls
      DROP CONSTRAINT platform_temporal_retention_current_receipt_tenant_fkey;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_retention_receipts
      DROP CONSTRAINT platform_temporal_retention_receipt_aggregate_tenant_fkey,
      DROP CONSTRAINT platform_temporal_retention_receipt_control_tenant_fkey;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_retention_controls
      DROP CONSTRAINT platform_temporal_retention_module_tenant_fkey,
      DROP CONSTRAINT platform_temporal_retention_aggregate_tenant_fkey;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_import_records
      DROP CONSTRAINT platform_temporal_import_module_tenant_fkey,
      DROP CONSTRAINT platform_temporal_import_revision_tenant_fkey,
      DROP CONSTRAINT platform_temporal_import_predecessor_tenant_fkey;
    """)

    execute("""
    ALTER TABLE platform_temporal_qualification_current_projections
      DROP CONSTRAINT platform_temporal_current_projection_revision_tenant_fkey,
      DROP CONSTRAINT platform_temporal_current_projection_aggregate_tenant_fkey;
    """)

    drop_if_exists(
      index(
        :platform_temporal_qualification_retention_receipts,
        [:id, :tenant_id, :control_id],
        name: "platform_temporal_retention_receipts_control_reference_index"
      )
    )

    drop_if_exists(
      index(
        :platform_temporal_qualification_retention_controls,
        [:id, :tenant_id, :aggregate_id],
        name: "platform_temporal_retention_controls_scope_reference_index"
      )
    )

    execute("""
    DROP TRIGGER platform_temporal_qualification_segment_guard
      ON platform_temporal_qualification_segments;
    """)

    execute("""
    DROP FUNCTION guard_platform_temporal_qualification_segment();
    """)

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_segments,
        :platform_temporal_segment_redaction_shape
      )
    )

    alter table(:platform_temporal_qualification_segments) do
      remove(:redaction_receipt_id)
      remove(:redacted_at)
    end

    execute("""
    DROP TRIGGER platform_temporal_retention_receipt_guard ON platform_temporal_qualification_retention_receipts;
    """)

    execute("""
    DROP FUNCTION guard_platform_temporal_retention_receipt();
    """)

    drop_if_exists(
      index(
        :platform_temporal_qualification_retention_receipts,
        [:tenant_id, :control_id, :version],
        name: "platform_temporal_retention_receipts_version_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_retention_receipts, [:id, :tenant_id],
        name: "platform_temporal_retention_receipts_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_retention_receipts,
        :platform_temporal_retention_receipt_operation_shape
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_retention_receipts,
        :platform_temporal_retention_receipt_reason_shape
      )
    )

    drop(table(:platform_temporal_qualification_retention_receipts))

    drop_if_exists(
      index(
        :platform_temporal_qualification_retention_controls,
        [:tenant_id, :module_key, :state],
        name: "platform_temporal_retention_controls_module_state_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_retention_controls, [:tenant_id, :aggregate_id],
        name: "platform_temporal_retention_controls_aggregate_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_retention_controls, [:id, :tenant_id],
        name: "platform_temporal_retention_controls_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_retention_controls,
        :platform_temporal_retention_state_shape
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_retention_controls,
        :platform_temporal_retention_window_valid
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_retention_controls,
        :platform_temporal_retention_policy_key_shape
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_retention_controls,
        :platform_temporal_retention_module_key_shape
      )
    )

    drop(table(:platform_temporal_qualification_retention_controls))

    execute("""
    DROP TRIGGER platform_temporal_import_record_guard ON platform_temporal_qualification_import_records;
    """)

    execute("""
    DROP FUNCTION guard_platform_temporal_import_record();
    """)

    drop_if_exists(
      index(:platform_temporal_qualification_import_records, [:tenant_id, :predecessor_record_id],
        name: "platform_temporal_import_records_successor_index"
      )
    )

    drop_if_exists(
      index(
        :platform_temporal_qualification_import_records,
        [:tenant_id, :source_snapshot_digest, :source_identifier_digest, :mapping_revision],
        name: "platform_temporal_import_records_source_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_import_records, [:tenant_id, :import_id, :version],
        name: "platform_temporal_import_records_version_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_import_records, [:id, :tenant_id],
        name: "platform_temporal_import_records_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_import_records,
        :platform_temporal_import_state_shape
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_import_records,
        :platform_temporal_import_mapping_revision_shape
      )
    )

    drop_if_exists(
      constraint(
        :platform_temporal_qualification_import_records,
        :platform_temporal_import_digest_shape
      )
    )

    drop(table(:platform_temporal_qualification_import_records))

    execute("""
    DROP TRIGGER platform_temporal_qualification_fact_guard
      ON platform_temporal_qualification_facts;
    """)

    execute("""
    DROP FUNCTION guard_platform_temporal_qualification_fact();
    """)

    drop_if_exists(
      constraint(:platform_temporal_qualification_facts, :platform_temporal_fact_redaction_shape)
    )

    create constraint(
             :platform_temporal_qualification_facts,
             :platform_temporal_fact_quantity_nonzero,
             check: """
               quantity <> 0
             """
           )

    alter table(:platform_temporal_qualification_facts) do
      remove(:redaction_receipt_id)
      remove(:redacted_at)
    end

    drop_if_exists(
      index(:platform_temporal_qualification_current_projections, [:tenant_id, :aggregate_id],
        name: "platform_temporal_current_projections_aggregate_index"
      )
    )

    drop_if_exists(
      index(:platform_temporal_qualification_current_projections, [:id, :tenant_id],
        name: "platform_temporal_current_projections_id_tenant_index"
      )
    )

    drop(table(:platform_temporal_qualification_current_projections))

    execute("""
    CREATE FUNCTION guard_platform_temporal_qualification_segment()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_segment_delete_forbidden',
          MESSAGE = 'temporal qualification segment deletion is forbidden';
      END IF;

      IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_segment_immutable',
          MESSAGE = 'temporal qualification segments are immutable';
      END IF;

      PERFORM pg_advisory_xact_lock(
        hashtextextended(
          'platform-temporal-qualification-segment:' ||
            NEW.tenant_id::text || ':' || NEW.revision_id::text,
          0
        )
      );

      IF EXISTS (
        SELECT 1
        FROM platform_temporal_qualification_segments AS segment
        WHERE segment.tenant_id = NEW.tenant_id
          AND segment.revision_id = NEW.revision_id
          AND NEW.effective_from < segment.effective_until
          AND segment.effective_from < NEW.effective_until
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23P01',
          CONSTRAINT = 'platform_temporal_qualification_segment_no_overlap',
          MESSAGE = 'temporal qualification segments overlap';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE FUNCTION guard_platform_temporal_qualification_fact()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      operation_kind text;
      operation_target uuid;
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_fact_delete_forbidden',
          MESSAGE = 'temporal qualification fact deletion is forbidden';
      END IF;

      IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_fact_immutable',
          MESSAGE = 'temporal qualification facts are immutable';
      END IF;

      NEW.recorded_at := transaction_timestamp() AT TIME ZONE 'UTC';

      SELECT kind, target_fact_id
      INTO operation_kind, operation_target
      FROM platform_temporal_qualification_fact_operations
      WHERE id = NEW.operation_id
        AND tenant_id = NEW.tenant_id
        AND scope_id = NEW.scope_id;

      IF operation_kind IS NULL THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_fact_operation_missing',
          MESSAGE = 'temporal qualification fact operation is missing';
      END IF;

      IF operation_kind = 'record' AND (
        NEW.kind <> 'entry'
        OR EXISTS (
          SELECT 1
          FROM platform_temporal_qualification_facts
          WHERE tenant_id = NEW.tenant_id
            AND operation_id = NEW.operation_id
        )
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_fact_record_shape',
          MESSAGE = 'record operation must create exactly one entry';
      END IF;

      IF operation_kind = 'reverse_and_replace' AND (
        (NEW.kind = 'reversal' AND (
          NEW.reverses_fact_id IS DISTINCT FROM operation_target
          OR EXISTS (
            SELECT 1
            FROM platform_temporal_qualification_facts
            WHERE tenant_id = NEW.tenant_id
              AND operation_id = NEW.operation_id
              AND kind = 'reversal'
          )
        ))
        OR
        (NEW.kind = 'entry' AND EXISTS (
          SELECT 1
          FROM platform_temporal_qualification_facts
          WHERE tenant_id = NEW.tenant_id
            AND operation_id = NEW.operation_id
            AND kind = 'entry'
        ))
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_fact_correction_shape',
          MESSAGE = 'correction operation fact shape is invalid';
      END IF;

      IF NEW.kind = 'reversal' AND NOT EXISTS (
        SELECT 1
        FROM platform_temporal_qualification_facts
        WHERE id = NEW.reverses_fact_id
          AND tenant_id = NEW.tenant_id
          AND scope_id = NEW.scope_id
          AND kind = 'entry'
      ) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'platform_temporal_qualification_fact_reversal_target',
          MESSAGE = 'temporal qualification reversal target is invalid';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER platform_temporal_qualification_segment_guard
    BEFORE INSERT OR UPDATE OR DELETE
    ON platform_temporal_qualification_segments
    FOR EACH ROW
    EXECUTE FUNCTION guard_platform_temporal_qualification_segment();
    """)

    execute("""
    CREATE TRIGGER platform_temporal_qualification_fact_guard
    BEFORE INSERT OR UPDATE OR DELETE
    ON platform_temporal_qualification_facts
    FOR EACH ROW
    EXECUTE FUNCTION guard_platform_temporal_qualification_fact();
    """)
  end
end
