defmodule Chimwemwe.Repo.Migrations.Phase2OpaqueSessionFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:identity_application_sessions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:actor_id, :uuid, null: false)

      add(
        :membership_id,
        references(:platform_tenant_memberships,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "identity_application_sessions_membership_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :external_identity_link_id,
        references(:identity_external_identity_links,
          column: :id,
          match: :simple,
          name: "identity_application_sessions_external_link_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:token_digest, :binary, null: false)
      add(:status, :text, null: false, default: "active")
      add(:assurance, :text, null: false)
      add(:assurance_at, :utc_datetime_usec, null: false)
      add(:idle_expires_at, :utc_datetime_usec, null: false)
      add(:absolute_expires_at, :utc_datetime_usec, null: false)
      add(:last_seen_at, :utc_datetime_usec, null: false)

      add(
        :rotated_to_session_id,
        references(:identity_application_sessions,
          column: :id,
          match: :simple,
          name: "identity_application_sessions_rotated_to_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )

      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(
             :identity_application_sessions,
             :identity_application_sessions_token_digest_sha256,
             check: """
               octet_length(token_digest) = 32
             """
           )

    create constraint(
             :identity_application_sessions,
             :identity_application_sessions_status_allowed,
             check: """
               status IN ('active', 'rotated', 'logged_out', 'revoked')
             """
           )

    create constraint(
             :identity_application_sessions,
             :identity_application_sessions_lock_version_positive,
             check: """
               lock_version >= 1
             """
           )

    create constraint(:identity_application_sessions, :identity_application_sessions_expiry_order,
             check: """
               idle_expires_at > inserted_at AND
             absolute_expires_at > idle_expires_at AND
             absolute_expires_at <= inserted_at + INTERVAL '12 hours'

             """
           )

    create constraint(
             :identity_application_sessions,
             :identity_application_sessions_rotation_consistent,
             check: """
               (status = 'rotated' AND rotated_to_session_id IS NOT NULL) OR
             (status IN ('active', 'logged_out', 'revoked') AND rotated_to_session_id IS NULL)

             """
           )

    create index(:identity_application_sessions, [:id, :tenant_id],
             name: "identity_application_sessions_id_tenant_index",
             unique: true
           )

    create index(:identity_application_sessions, [:token_digest],
             name: "identity_application_sessions_token_digest_index",
             unique: true
           )

    create index(
             :identity_application_sessions,
             [:tenant_id, :actor_id, :status, :absolute_expires_at],
             name: "identity_application_sessions_actor_status_index"
           )
  end

  def down do
    drop_if_exists(
      index(
        :identity_application_sessions,
        [:tenant_id, :actor_id, :status, :absolute_expires_at],
        name: "identity_application_sessions_actor_status_index"
      )
    )

    drop_if_exists(
      index(:identity_application_sessions, [:token_digest],
        name: "identity_application_sessions_token_digest_index"
      )
    )

    drop_if_exists(
      index(:identity_application_sessions, [:id, :tenant_id],
        name: "identity_application_sessions_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :identity_application_sessions,
        :identity_application_sessions_rotation_consistent
      )
    )

    drop_if_exists(
      constraint(:identity_application_sessions, :identity_application_sessions_expiry_order)
    )

    drop_if_exists(
      constraint(
        :identity_application_sessions,
        :identity_application_sessions_lock_version_positive
      )
    )

    drop_if_exists(
      constraint(:identity_application_sessions, :identity_application_sessions_status_allowed)
    )

    drop_if_exists(
      constraint(
        :identity_application_sessions,
        :identity_application_sessions_token_digest_sha256
      )
    )

    drop(
      constraint(:identity_application_sessions, "identity_application_sessions_rotated_to_fkey")
    )

    drop(
      constraint(
        :identity_application_sessions,
        "identity_application_sessions_external_link_fkey"
      )
    )

    drop(
      constraint(
        :identity_application_sessions,
        "identity_application_sessions_membership_tenant_fkey"
      )
    )

    drop(table(:identity_application_sessions))
  end
end
