defmodule Chimwemwe.Repo.Migrations.CorrectSupportSessionReference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(
      constraint(
        :identity_support_access_grants,
        "identity_support_access_grants_session_tenant_fkey"
      )
    )

    alter table(:identity_support_access_grants) do
      modify(
        :session_id,
        references(:identity_application_sessions,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "identity_support_access_grants_session_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end
  end

  def down do
    drop(
      constraint(
        :identity_support_access_grants,
        "identity_support_access_grants_session_tenant_fkey"
      )
    )

    alter table(:identity_support_access_grants) do
      modify(
        :session_id,
        references(:identity_application_sessions,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "identity_support_access_grants_session_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end
  end
end
