defmodule Chimwemwe.Repo.Migrations.AddOrganizationLegalLifecycleFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:organization_legal_entity_relationship_terminations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)

      add(
        :relationship_id,
        references(:organization_legal_entity_relationships,
          column: :id,
          with: [tenant_id: :tenant_id],
          match: :full,
          name: "org_legal_rel_terminations_relationship_tenant_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:effective_until, :date, null: false)
      add(:evidence_reference, :text, null: false)
      add(:recorded_by_actor_id, :uuid, null: false)
      add(:recorded_at, :utc_datetime_usec, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(
             :organization_legal_entity_relationship_terminations,
             :org_legal_rel_terminations_evidence_reference_length,
             check: """
               char_length(evidence_reference) BETWEEN 1 AND 120
             """
           )

    create index(:organization_legal_entity_relationship_terminations, [:id, :tenant_id],
             name: "organization_legal_relationship_terminations_id_tenant_index",
             unique: true
           )

    create index(
             :organization_legal_entity_relationship_terminations,
             [:tenant_id, :relationship_id],
             name: "organization_legal_relationship_terminations_relationship_index",
             unique: true
           )

    execute("""
    CREATE FUNCTION organization_legal_validate_relationship_termination()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      relationship_start date;
    BEGIN
      PERFORM pg_advisory_xact_lock(
        hashtextextended(
          'organization-legal-relationship-termination:' ||
            NEW.tenant_id::text || ':' || NEW.relationship_id::text,
          0
        )
      );

      SELECT effective_from
      INTO relationship_start
      FROM organization_legal_entity_relationships
      WHERE tenant_id = NEW.tenant_id
        AND id = NEW.relationship_id;

      IF NOT FOUND THEN
        RAISE EXCEPTION USING
          ERRCODE = '23503',
          CONSTRAINT = 'org_legal_rel_terminations_relationship_tenant_fkey',
          MESSAGE = 'relationship termination target is unavailable';
      END IF;

      IF NEW.effective_until <= relationship_start THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'organization_legal_relationship_terminations_interval_valid',
          MESSAGE = 'relationship termination must be later than its effective start';
      END IF;

      NEW.recorded_at := transaction_timestamp() AT TIME ZONE 'UTC';
      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER organization_legal_relationship_terminations_validate
    BEFORE INSERT
    ON organization_legal_entity_relationship_terminations
    FOR EACH ROW
    EXECUTE FUNCTION organization_legal_validate_relationship_termination();
    """)

    execute("""
    CREATE TRIGGER organization_legal_relationship_terminations_immutable
    BEFORE UPDATE OR DELETE
    ON organization_legal_entity_relationship_terminations
    FOR EACH ROW
    EXECUTE FUNCTION organization_legal_reject_structure_fact_mutation();
    """)

    execute("""
    CREATE FUNCTION organization_legal_validate_corporate_unit_profile_revision()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      previous_revision bigint;
    BEGIN
      PERFORM pg_advisory_xact_lock(
        hashtextextended(
          'organization-legal-corporate-unit-profile:' ||
            NEW.tenant_id::text || ':' || NEW.corporate_unit_id::text,
          0
        )
      );

      SELECT max(revision_number)
      INTO previous_revision
      FROM organization_legal_corporate_unit_profile_revisions
      WHERE tenant_id = NEW.tenant_id
        AND corporate_unit_id = NEW.corporate_unit_id;

      IF NEW.revision_number <> COALESCE(previous_revision, 0) + 1 THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'organization_legal_corporate_unit_profiles_revision_chain',
          MESSAGE = 'corporate unit profile revision must be consecutive';
      END IF;

      NEW.recorded_at := transaction_timestamp() AT TIME ZONE 'UTC';
      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER organization_legal_corporate_unit_profiles_validate_revision
    BEFORE INSERT
    ON organization_legal_corporate_unit_profile_revisions
    FOR EACH ROW
    EXECUTE FUNCTION organization_legal_validate_corporate_unit_profile_revision();
    """)
  end

  def down do
    execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM organization_legal_entity_relationship_terminations LIMIT 1
      ) OR EXISTS (
        SELECT 1
        FROM organization_legal_corporate_unit_profile_revisions
        WHERE revision_number > 1
        LIMIT 1
      ) OR EXISTS (
        SELECT 1
        FROM platform_authority_audit_events
        WHERE action_name IN (
          'organization.legal.relationship.end',
          'organization.legal.corporate_unit.profile.revise'
        )
        LIMIT 1
      ) OR EXISTS (
        SELECT 1
        FROM platform_outbox_events
        WHERE event_type IN (
          'organization.legal.relationship.ended',
          'organization.legal.corporate_unit.profile_revised'
        )
        LIMIT 1
      ) THEN
        RAISE EXCEPTION 'refusing to roll back organization legal lifecycle state or evidence';
      END IF;
    END;
    $$;
    """)

    execute("""
    DROP TRIGGER IF EXISTS organization_legal_corporate_unit_profiles_validate_revision
    ON organization_legal_corporate_unit_profile_revisions;
    """)

    execute(
      "DROP FUNCTION IF EXISTS organization_legal_validate_corporate_unit_profile_revision()"
    )

    execute("""
    DROP TRIGGER IF EXISTS organization_legal_relationship_terminations_immutable
    ON organization_legal_entity_relationship_terminations;
    """)

    execute("""
    DROP TRIGGER IF EXISTS organization_legal_relationship_terminations_validate
    ON organization_legal_entity_relationship_terminations;
    """)

    execute("DROP FUNCTION IF EXISTS organization_legal_validate_relationship_termination()")

    drop_if_exists(
      index(:organization_legal_entity_relationship_terminations, [:tenant_id, :relationship_id],
        name: "organization_legal_relationship_terminations_relationship_index"
      )
    )

    drop_if_exists(
      index(:organization_legal_entity_relationship_terminations, [:id, :tenant_id],
        name: "organization_legal_relationship_terminations_id_tenant_index"
      )
    )

    drop_if_exists(
      constraint(
        :organization_legal_entity_relationship_terminations,
        :org_legal_rel_terminations_evidence_reference_length
      )
    )

    drop(
      constraint(
        :organization_legal_entity_relationship_terminations,
        "org_legal_rel_terminations_relationship_tenant_fkey"
      )
    )

    drop(table(:organization_legal_entity_relationship_terminations))
  end
end
