defmodule Chimwemwe.Repo.Migrations.IdentityAuthenticationFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    create table(:identity_accounts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :text, null: false)
      add(:hashed_password, :text, null: false)
      add(:status, :text, null: false, default: "active")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:identity_accounts, [:email],
             name: "identity_accounts_unique_email_index"
           )

    create constraint(:identity_accounts, :identity_accounts_status_allowed,
             check: """
               status IN ('active', 'suspended')
             """
           )

    create table(:identity_sso_connections, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :uuid, null: false)
      add(:name, :text, null: false)
      add(:provider, :text, null: false)
      add(:issuer_url, :text, null: false)
      add(:client_id, :text, null: false)
      add(:secret_reference, :text, null: false)
      add(:allowed_domains, :text, null: false, default: "")
      add(:connection_status, :text, null: false, default: "draft")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:identity_sso_connections, :identity_sso_connections_provider_allowed,
             check: """
               provider IN ('google', 'microsoft', 'oidc', 'saml')
             """
           )

    create constraint(:identity_sso_connections, :identity_sso_connections_status_allowed,
             check: """
               connection_status IN ('draft', 'active', 'disabled')
             """
           )

    create index(:identity_sso_connections, [:tenant_id, :name],
             name: "identity_sso_connections_tenant_name_index",
             unique: true
           )

    create table(:identity_tokens, primary_key: false) do
      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:extra_data, :map)
      add(:purpose, :text, null: false)
      add(:expires_at, :utc_datetime, null: false)
      add(:subject, :text, null: false)
      add(:jti, :text, null: false, primary_key: true)
    end
  end

  def down do
    drop(table(:identity_tokens))

    drop_if_exists(
      index(:identity_sso_connections, [:tenant_id, :name],
        name: "identity_sso_connections_tenant_name_index"
      )
    )

    drop_if_exists(
      constraint(:identity_sso_connections, :identity_sso_connections_status_allowed)
    )

    drop_if_exists(
      constraint(:identity_sso_connections, :identity_sso_connections_provider_allowed)
    )

    drop(table(:identity_sso_connections))

    drop_if_exists(constraint(:identity_accounts, :identity_accounts_status_allowed))

    drop_if_exists(
      unique_index(:identity_accounts, [:email], name: "identity_accounts_unique_email_index")
    )

    drop(table(:identity_accounts))
  end
end
