defmodule Chimwemwe.Repo.Migrations.AddInstitutionalGuards do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE FUNCTION institution_identity_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
    IF TG_OP = 'DELETE' THEN RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'institution deletion forbidden'; END IF;
    IF TG_OP = 'INSERT' THEN
    IF NEW.status <> 'draft' OR NEW.lock_version <> 1 OR NOT EXISTS (SELECT 1 FROM pg_timezone_names WHERE name = NEW.time_zone) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid initial institution';
    END IF;
    ELSE
    IF ROW(NEW.id, NEW.tenant_id, NEW.display_name, NEW.classification, NEW.time_zone, NEW.inserted_at)
    IS DISTINCT FROM ROW(OLD.id, OLD.tenant_id, OLD.display_name, OLD.classification, OLD.time_zone, OLD.inserted_at)
    OR OLD.status <> 'draft' OR NEW.lock_version <> OLD.lock_version + 1 THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid institutional transition';
    END IF;
    END IF;
    RETURN NEW;
    END $$;
    """)

    execute("""
    CREATE FUNCTION institution_fact_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'institutional facts are immutable';
    END $$;
    """)

    execute("""
    CREATE FUNCTION institution_consistency_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE
    unit_id uuid; unit_tenant uuid; version bigint; assignment uuid; publication uuid; selected_assignment uuid;
    BEGIN
    IF TG_TABLE_NAME = 'institutional_units' THEN unit_id := NEW.id; ELSE unit_id := NEW.institutional_unit_id; END IF;
    unit_tenant := NEW.tenant_id;
    SELECT lock_version INTO version FROM institutional_units WHERE id = unit_id AND tenant_id = unit_tenant FOR UPDATE;
    SELECT id INTO assignment FROM institution_initial_operator_assignments WHERE institutional_unit_id = unit_id AND tenant_id = unit_tenant;
    SELECT id, operator_assignment_id INTO publication, selected_assignment FROM institution_publications WHERE institutional_unit_id = unit_id AND tenant_id = unit_tenant;
    IF version IS NULL OR
    (version = 1 AND (assignment IS NOT NULL OR publication IS NOT NULL)) OR
    (version = 2 AND (assignment IS NULL OR publication IS NOT NULL)) OR
    (version = 3 AND (assignment IS NULL OR publication IS NULL OR selected_assignment IS DISTINCT FROM assignment)) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'inconsistent institutional lifecycle';
    END IF;
    RETURN NEW;
    END $$;
    """)

    execute("""
    CREATE TRIGGER institution_identity_trigger BEFORE INSERT OR UPDATE OR DELETE ON institutional_units FOR EACH ROW EXECUTE FUNCTION institution_identity_guard();
    """)

    execute("""
    CREATE TRIGGER institution_initial_operator_assignments_immutable BEFORE UPDATE OR DELETE ON institution_initial_operator_assignments FOR EACH ROW EXECUTE FUNCTION institution_fact_guard();
    """)

    execute("""
    CREATE TRIGGER institution_publications_immutable BEFORE UPDATE OR DELETE ON institution_publications FOR EACH ROW EXECUTE FUNCTION institution_fact_guard();
    """)

    execute("""
    CREATE CONSTRAINT TRIGGER institutional_units_consistent AFTER INSERT OR UPDATE ON institutional_units DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION institution_consistency_guard();
    """)

    execute("""
    CREATE CONSTRAINT TRIGGER institution_initial_operator_assignments_consistent AFTER INSERT OR UPDATE ON institution_initial_operator_assignments DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION institution_consistency_guard();
    """)

    execute("""
    CREATE CONSTRAINT TRIGGER institution_publications_consistent AFTER INSERT OR UPDATE ON institution_publications DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION institution_consistency_guard();
    """)
  end

  def down do
    execute("""
    DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM institutional_units)
         OR EXISTS (SELECT 1 FROM platform_authority_audit_events WHERE action_name LIKE 'institution.structure.%')
         OR EXISTS (SELECT 1 FROM platform_outbox_events WHERE aggregate_type = 'institution.structure.unit')
         OR EXISTS (SELECT 1 FROM platform_authority_action_idempotency WHERE action_name LIKE 'institution.structure.%') THEN
        RAISE EXCEPTION 'retained institutional foundation cannot be rolled back';
      END IF;
    END $$;
    """)

    execute("""
    DROP TRIGGER institution_publications_consistent ON institution_publications;
    """)

    execute("""
    DROP TRIGGER institution_initial_operator_assignments_consistent ON institution_initial_operator_assignments;
    """)

    execute("""
    DROP TRIGGER institutional_units_consistent ON institutional_units;
    """)

    execute("""
    DROP TRIGGER institution_publications_immutable ON institution_publications;
    """)

    execute("""
    DROP TRIGGER institution_initial_operator_assignments_immutable ON institution_initial_operator_assignments;
    """)

    execute("""
    DROP TRIGGER institution_identity_trigger ON institutional_units;
    """)

    execute("""
    DROP FUNCTION institution_consistency_guard();
    """)

    execute("""
    DROP FUNCTION institution_fact_guard();
    """)

    execute("""
    DROP FUNCTION institution_identity_guard();
    """)
  end
end
