defmodule Chimwemwe.Repo.Migrations.ConstrainInstitutionalEvidence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE FUNCTION institution_proof_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE
    u institutional_units%ROWTYPE;
    a institution_initial_operator_assignments%ROWTYPE;
    proof jsonb; local_day date; expected_revision bigint; legal_version bigint;
    BEGIN
    SELECT * INTO STRICT u FROM institutional_units WHERE id = NEW.institutional_unit_id AND tenant_id = NEW.tenant_id FOR UPDATE;
    local_day := (statement_timestamp() AT TIME ZONE u.time_zone)::date;
    proof := NEW.verification;
    IF TG_TABLE_NAME = 'institution_initial_operator_assignments' THEN
    a := NEW;
    expected_revision := 1;
    ELSE
    SELECT * INTO STRICT a FROM institution_initial_operator_assignments WHERE id = NEW.operator_assignment_id AND tenant_id = NEW.tenant_id;
    expected_revision := 2;
    IF a.institutional_unit_id <> u.id OR a.effective_from <> local_day THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'publication basis mismatch';
    END IF;
    END IF;
    SELECT lock_version INTO legal_version FROM organization_legal_entities WHERE id = a.legal_entity_id AND tenant_id = a.tenant_id AND status = 'active' FOR SHARE;
    IF u.status <> 'draft' OR u.lock_version <> expected_revision OR legal_version IS DISTINCT FROM a.legal_entity_version THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'stale institutional basis';
    END IF;
    IF (jsonb_typeof(proof) = 'object'
    AND proof->>'tenant_id' = NEW.tenant_id::text
    AND proof->>'institutional_unit_id' = u.id::text
    AND (proof->>'institution_version')::bigint = expected_revision
    AND proof->>'legal_entity_id' = a.legal_entity_id::text
    AND (proof->>'legal_entity_version')::bigint = legal_version
    AND proof->>'evidence_reference' = a.evidence_reference::text
    AND (proof->>'effective_from')::date = a.effective_from
    AND proof->>'policy_key' = 'synthetic.cf1.initial_operator.v1'
    AND proof->>'jurisdiction' = 'ZZ'
    AND proof->>'evidence_type' = 'synthetic_operating_instrument'
    AND proof->>'impact_policy' = 'cf1.initial_unpublished_root.v1'
    AND proof->'conditions_satisfied' = 'true'::jsonb
    AND proof->'impact_accepted' = 'true'::jsonb
    AND proof->'consumer_keys' = '[]'::jsonb
    AND (proof->>'evidence_version')::uuid IS NOT NULL
    AND (proof->>'issuer_reference')::uuid IS NOT NULL
    AND (proof->>'verifier_actor_id')::uuid IS NOT NULL
    AND (proof->>'impact_reference')::uuid IS NOT NULL
    AND (proof->>'checked_at')::timestamptz >= transaction_timestamp()
    AND (proof->>'checked_at')::timestamptz <= clock_timestamp()
    AND local_day - (proof->>'status_checked_on')::date BETWEEN 0 AND 30
    AND (proof->>'valid_from')::date <= local_day
    AND (proof->>'valid_from')::date <= a.effective_from
    AND (proof->>'valid_until')::date > local_day
    AND (proof->>'valid_until')::date > a.effective_from) IS DISTINCT FROM TRUE THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid institutional proof';
    END IF;
    RETURN NEW;
    END $$;
    """)

    execute("""
    CREATE TRIGGER institution_initial_operator_assignments_proof BEFORE INSERT ON institution_initial_operator_assignments FOR EACH ROW EXECUTE FUNCTION institution_proof_guard();
    """)

    execute("""
    CREATE TRIGGER institution_publications_proof BEFORE INSERT ON institution_publications FOR EACH ROW EXECUTE FUNCTION institution_proof_guard();
    """)
  end

  def down do
    execute("""
    DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM institutional_units)
         OR EXISTS (SELECT 1 FROM platform_authority_audit_events WHERE action_name LIKE 'institution.structure.%')
         OR EXISTS (SELECT 1 FROM platform_outbox_events WHERE aggregate_type = 'institution.structure.unit')
         OR EXISTS (SELECT 1 FROM platform_authority_action_idempotency WHERE action_name LIKE 'institution.structure.%') THEN
        RAISE EXCEPTION 'retained institutional foundation cannot be rolled back';
      END IF;
    END $$;
    """)

    execute("""
    DROP TRIGGER institution_publications_proof ON institution_publications;
    """)

    execute("""
    DROP TRIGGER institution_initial_operator_assignments_proof ON institution_initial_operator_assignments;
    """)

    execute("""
    DROP FUNCTION institution_proof_guard();
    """)
  end
end
